### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by colingonglin** [GitbookIO/gitbook#1322] opened 2016-05-24 11:38 UTC
After my last commit, the book failed in the code that I have not modified for a long time.

And the build shows a lot of error mesages:
SVG - Unknown character: U+683C in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+6210 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+4EA4 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+6570 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+91CF in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+6D6E in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+52A8 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+76C8 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+4E8F in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+FF08 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+6700 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+65B0 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+4EF7 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+6301 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+4ED3 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+6210 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+672C in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+FF09 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+6301 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+4ED3 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+6570 in MathJax_Main,MathJax_Size1,MathJax_AMS
SVG - Unknown character: U+91CF in MathJax_Main,MathJax_Size1,MathJax_AMS

Here is my book:
Report Infos Book: gonglin/requirementsspecification, Book ID: 56fe380f3c9ac01000fbc806, Build ID: 57443b02b9bb4f10007ef9a9, Version 9cf4b33de334ed0b0e2fef27f96baea581480db3 and Stack gitbook/builder:1.5.0.

**Comment by SamyPesse** [comment] 2016-05-24 12:24
Duplicate of #1279

If it works in 2.6.7, you can switch back to in your GitBook.com book settings:

![screen shot 2016-05-24 at 10 44 41](https://cloud.githubusercontent.com/assets/845425/15503660/3c1b2dc0-21bb-11e6-91d5-60a335c96d82.png)

**Closed by SamyPesse** 2016-05-24 12:24 UTC
