### ISSUE TITLE
Gitbook Editor won't open / Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by prefontaine** [GitbookIO/gitbook#1976] opened 2018-02-02 00:25 UTC
### Current behavior: Gitbook Editor won't open

I'm running and downladed the Gitbook Editor (https://www.gitbook.com/editor/linux-64-bit/download). It seemed to install fine but when I click on the icon to open it nothing happens.

I'm running: Ubuntu 16.04.3 LTS / xenial on a Dell XPS 13

### Expected behavior

The app should open so I can configure and use it.

**Comment by zcdll** [comment] 2018-02-08 08:51
me too

**Comment by zcdll** [comment] 2018-02-08 09:01
I had the same problem either, then I tried to search with Google and I found this page [How To Install GitBook Editor On Ubuntu 16.04](https://www.linuxhelp.com/how-to-install-gitbook-editor-on-ubuntu-16-04/) 

I tried to follow the instructions to run the two commands below, finally I succeeded in installing Gitbook-editor.

```
wget http://downloads.editor.gitbook.com/download/linux-64-bit

dpkg -i linux-64-bit
```

**Comment by norbertfuhs** [comment] 2018-03-31 14:16
Is this issue with the Gitbook Editor on Ubuntu 16.04.3 still open?

**Comment by zcdll** [comment] 2018-03-31 14:20
@norbertfuhs you can see the comment I posted above. I succeeded in installing Gitbook-editor by following the instructions in [How To Install GitBook Editor On Ubuntu 16.04](https://github.com/GitbookIO/gitbook/issues/1976#issuecomment-377696071)   

You could have a try.

**Comment by norbertfuhs** [comment] 2018-03-31 14:27
Thanks for the info @zcdll I also use the Editor on Ubuntu but I think if the issue is closed someone should close it..

**Comment by zcdll** [comment] 2018-03-31 15:05
@norbertfuhs  Yeah, someone should close it.  

@prefontaine Do you have any problem with the issue?

**Comment by norbertfuhs** [comment] 2018-04-04 13:37
@prefontaine Hi I have no problem with this issue but if an issue is solved I think it should be closed..

Also I think man issues here are related to Gitbook 3.2.3 and when the new version of Gitbook is up with an new Editor many issues will be solved in the next months.

You can check the upcoming Version of Gitbook with this link if you like: [https://beta.gitbook.com/](https://beta.gitbook.com/)

**Comment by Riseley** [comment] 2018-04-24 21:01
16.04.3 LTS, same error.

**Closed** 2024-03-25 09:42 UTC
