### ISSUE TITLE
Don't fail on ToC entries that link to a directory

### ISSUE THREAD

**Issue by Niefee** [GitbookIO/gitbook#1551] opened 2016-10-05 11:03 UTC
my gitbook can not update.
it always show the error

```
error: error while parsing page "2016/1": 

Error: EISDIR: illegal operation on a directory, read
```

the  website:https:// www.gitbook.com/book/niefee/my-study-records/activity

**Comment by nagim** [comment] 2016-10-06 06:54
Hi,

Checked you repo and found the problem.
These kind of lines in the `summary.md` will not work with the latest (>=3.2.2) version:
`* [1](2016/1)`

Basically the problem is that the parser expects files in the links, but the way you used it, it thinks it's a directory.
The error message refers to this problem.

What you need to do to correct is to write it like this:
```
* [2016](2016/SUMMARY.md)
    * 1
        * [2016年1月3日](2016/1/2016年1月3日.markdown)
        * [2016年1月4日](2016/1/2016年1月4日.markdown)
```
So no need to use the link syntax, just write the text you want to display in the ToC.
Use the same for the similar lines.

I hope it's clear.

Cheers,
Imre

**Comment by Niefee** [comment] 2016-10-06 13:12
Thank you very much, problem solved. This is my first question, I am a developer from China.

**Comment by nagim** [comment] 2016-10-07 07:33
No problem! :)

Could you please close this issue, if the problem is solved?

**Comment by Soreine** [comment] 2016-12-21 09:45
I reopen this issue, since the error message is not clear at all from the user point of view. I think we should instead fail with a proper error message, or simply ignore the link and display a warning.

**Closed** 2024-03-25 09:50 UTC
Labels: bug
