### ISSUE TITLE
Table of Contents not able to be expanded or open subchapters

### ISSUE THREAD

**Issue by chrisjake** [GitbookIO/gitbook#1720] opened 2017-02-18 00:21 UTC
### What is the current behavior?
Cannot display subchapters using the table of contents in gitbook editor 7.0.1.

e.g.
* Chapter 1 \\\will display
* Chapter 2 \\\ will display, and can be expanded
     * Chapter 2.2 \\\will not display, but cannot be expanded
          * Chapter 2.2.1 \\\cannot be seen (as can't be expanded)
* Chapter 3 \\\will display

Files can be opened using the files list.

### What is the expected behavior?
Table of contents can be fully expanded and all files opened.

**Comment by AaronO** [comment] 2017-02-18 00:30
@chrisjake This is a duplicate of GitbookIO/feedback#366

It's been fixed in our `master` and should ship soon: https://github.com/GitbookIO/feedback/issues/366#issuecomment-280802276

**Closed by AaronO** 2017-02-18 00:30 UTC
