### ISSUE TITLE
Summary files in subdirectories no longer supported

### ISSUE THREAD

**Issue by jonas** [GitbookIO/gitbook#1030] opened 2015-11-25 17:04 UTC
Given a `book.json` with the following

``` json
{
  "gitbook": "2.x.x",
  "output": "target/book",
  "structure": {
    "summary": "doc/toc.md"
  },
  ...
}
```

Gitbook errors out with `No SUMMARY file` when using any version above gitbook 2.5.2.

It looks like commit e38f3bb88423a17a7d0b292d86805a37f72cbff2 broke the ability to use a summary file located in a subdirectory of the root directory. Instead of the `fileExists` check it now only checks the root directory using `readdir`.

**Comment by maxkoryukov** [comment] 2017-02-19 12:31
Looks like this is a **duplicate of #1244**

**Closed** 2024-03-25 09:55 UTC
