### ISSUE TITLE
random errors when using gitbook plugin on running "gitbook serve".

### ISSUE THREAD

**Issue by sachetsharma** [GitbookIO/gitbook#1309] opened 2016-05-18 19:11 UTC
We are running gitbook with some plugins. Plugins are loaded fine but at the end it errors out with different error messages. All of them complains about one or the other plugin file missing. Running gitbook version 2.1.3 on windows 7.

info: 7 plugins are installed
info: loading plugin "prism"... OK
info: loading plugin "edit-link"... OK
info: loading plugin "livereload"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 66 pages
info: found 83 asset files

Error: ENOENT: no such file or directory, stat 'C:\Projects\myproject_book\gitbook\gitbook-plugin-fontsettings\buttons.js'

Error: ENOENT: no such file or directory, stat 'C:\Projects\myproject_book\gitbook\gitbook-plugin-lunr\lunr.min.js'

Error: ENOENT: no such file or directory, stat 'C:\Projects\myproject_book\gitbook\gitbook-plugin-livereload\plugin.js'

**Comment by SamyPesse** [comment] 2016-05-18 22:00
Can you paste me the output of `gitbook current` inside the book's directory?

**Comment by SamyPesse** [comment] 2016-05-19 08:36
And also the output of `node -v` ?

**Comment by sachetsharma** [comment] 2016-05-19 13:02
here is the output 

C:\Projects\myproject\\_book>gitbook current
GitBook version is 2.6.7

C:\Projects\myproject\\_book>node -v
v4.2.2

**Comment by SamyPesse** [comment] 2016-05-19 13:16
Run `gitbook current` inside the `C:\Projects\myproject` (I guess this is folder where your content is stored), and paste me the output.

**Comment by sachetsharma** [comment] 2016-05-19 13:19
Here it is:
C:\Projects\myproject>gitbook current
GitBook version is 3.0.0-pre.15

**Comment by SamyPesse** [comment] 2016-05-19 13:25
Ok thanks, I'll investigate and fix this.

**Comment by fractalf** [comment] 2016-05-31 13:34
I get the same..
```
alf@dev [~/gitbook] gitbook init ./foobar
warn: no summary file in this book
info: create README.md
info: create SUMMARY.md
info: initialization is finished
alf@dev [~/gitbook] cd foobar/
alf@dev [~/gitbook/foobar] node -v
v4.4.5
alf@dev [~/gitbook/foobar] gitbook current
GitBook version is 3.0.3
alf@dev [~/gitbook/foobar] gitbook build
info: 6 plugins are installed
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 1 pages
info: found 0 asset files

Error: ENOENT: no such file or directory, stat '/nfs/home/alf/gitbook/foobar/_book/gitbook/gitbook-plugin-lunr/lunr.min.js'

```

**Comment by superbull** [comment] 2016-06-03 11:50
I have the same problem in Windows7.
```
gitbook version: 3.0.3
node version: v5.5.0
```
I found that when the error message said:
```
Error: ENOENT: no such file or directory, stat '/nfs/home/alf/gitbook/foobar/_book/gitbook/gitbook-plugin-lunr/lunr.min.js'
```
the file `lunr.min.js` is there, but the size of this file is **0**.

**Comment by xNok** [comment] 2016-06-09 02:00
I have the similar problems in Windows7

```
Error: EPERM: operation not permitted, mkdir 'D:\www2\thinxtraPortal\cssb\_book'

Error: EPERM: operation not permitted, open 'D:\www2\thinxtraPortal\cssb\_book\part1-automated-workflow\cssb_automated_workflow.md'

Error: EPERM: operation not permitted, lstat 'D:\www2\thinxtraPortal\cssb\_book'
```

> gitbook version: 3.1.0
> node version: v5.6.0

The first thing I haved notice is that gitbook create a **read only `_book` directory**.
This seems to solve the 2 first issues but not the last one with `lstat`

**Comment by mdotasia** [comment] 2016-06-17 15:28
I get the same on Windows 7 with GitBook 3.1.1 and Node 6.2.1.

**Comment by takao-mizuno** [comment] 2016-07-12 00:16
I ran into the same problem on Windows7 with GitBook 3.1.0 and Node 6.3.0.
How's this problem going ?

**Comment by zargex** [comment] 2016-07-13 14:47
Hi, I have the same error, but in Linux 
```
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 7 plugins are installed 
info: 6 explicitly listed 
info: loading plugin "livereload"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 1 pages 
info: found 0 asset files 

Error: ENOENT: no such file or directory, stat '/home/aparra/Documentos/zoi-api/book/_book/gitbook/gitbook-plugin-livereload/plugin.js'
```
`gitbook --version
CLI version: 2.3.0
GitBook version: 3.2.0
`

`node --version
v4.4.7
`
But I looked at that directory and there is plugin.js, so I don't understand.
Thanks

**Comment by letmaik** [comment] 2016-07-14 10:34
Same:
```
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 7 plugins are installed
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 12 pages
info: found 15 asset files

Error: ENOENT: no such file or directory, stat '...\_book\gitbook\gitbook-plugin-fontsettings\fontsettings.js'
```

Everytime a different file.

**Comment by hamdichau** [comment] 2016-07-19 03:50
The same.

**Comment by eyinsma** [comment] 2016-08-04 07:00
The same issue on Windows 7.
GitBook version is 3.2.0
Node v6.3.1

**Comment by tanbro** [comment] 2016-08-09 03:19
The same error on windows 10 when auto restarting server

node v4.4.7, gitbook 3.2.0

```
Starting server ...
Serving book on http://localhost:4000
Restart after change in file SUMMARY.md

Stopping server

Error: EPERM: operation not permitted, mkdir 'D:\repos\yunhuni-server-api-docs\_book'
```

**Comment by liutopsec** [comment] 2016-08-19 09:47
Error: ENOENT: no such file or directory, stat 'D:\topsecgitbook\_book\gitbook\gitbook-plugin-fontsettings\fontsettings.js'

**Comment by liutopsec** [comment] 2016-08-19 09:47
```
Error: ENOENT: no such file or directory, stat 'D:\topsecgitbook\_book\gitbook\gitbook-plugin-fontsettings\fontsettings.js'
```

**Comment by fangzhouxin** [comment] 2016-08-24 04:26
I have the same problem with @liutopsec, I used docker to run gitbook serve command.

**Comment by yeszao** [comment] 2016-08-25 12:31
I had same problem with nodejs 0.10.46 on linux. But everything was fine when I switch to windows an build with Nodejs 4.5.0

**Comment by kuake** [comment] 2016-09-02 01:58
the same problem on windows 7
node v6.3.1
GitBook version is 3.2.0

**Comment by lesstif** [comment] 2016-09-02 07:28
i had same error on windows 7.

- node v4.5.0
- gitbook 3.2.0

**Comment by dstelljes** [comment] 2016-09-19 02:26
Same error on Fedora. Seems (for me, at least) that it's caused by disk latency: My working directory is on a network drive, but when I build in `/tmp` (local) there are no problems.

**Comment by zargex** [comment] 2016-09-19 13:05
I think the same @dstelljes, in my case my home is imported from a NFS server and (like you) working in local folder there are no problems.

**Comment by zhilidali** [comment] 2016-09-20 10:35
I had same error on windows 7.
*	node v4.5.0
*	gitbook 3.2.0

Is it because of NVM cause?

**Comment by hfxu** [comment] 2016-09-22 05:00
I had same problem with **gitbook build** or **serve** command.And I found that the default search plugin **lunr** may caused error.
At last,I had add [swiftype plugin](https://plugins.gitbook.com/plugin/swiftype) to sovle this problem.
Here is the config of my book.json.
```
{
   "plugins": [
      "swiftype"
   ],
   "pluginsConfig": {
      "swiftype": {
         "token": "utQHy1R2XyiVqDqaZxxx",
         "version": "2.0.0"
      }
   }
}
``` 
You need to run **gitbook install** command to install the plugin before build your books.

My env:
- Node 4.5.0
- gitbook 3.2.0
- npm 2.15.9

I hope this would help you.

**Comment by hfxu** [comment] 2016-09-22 07:22
Just now,I found it would be a problem of npm's config probelm.I found the solution at the [http://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows](http://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows).There is no need to add additional plugins.
Here is the quote from the anwser:
```
1. Run cmd as administrator 
2. Run npm config edit (You will get notepad editor)
3. Change Prefix variable to 'C:\Users\<User Name>\AppData\Roaming\npm'
```
This works fine for me.

**Comment by zargex** [comment] 2016-09-22 14:14
Hi @hfxu, i tried your solution and saddly didn't work for me.

**Comment by wei1306** [comment] 2016-09-23 04:24
I had same error on windows 7
gitbook 3.2.0
npm 3.3.6
node 5.0.0

`D:\Users\dounai\soc_book>gitbook serve
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 7 plugins are installed
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 8 pages
info: found 7 asset files

Error: ENOENT: no such file or directory, stat 'D:\Users\dounai\soc_book\_book\gi
tbook\gitbook-plugin-lunr\lunr.min.js'

D:\Users\dounai\soc_book>`

**Comment by sam-falvo** [comment] 2016-10-16 23:47
Getting the same issue on Ubuntu Linux.

```bash
kc5tja@enif:~/git/polaris/docs$ node -v
v4.4.2
kc5tja@enif:~/git/polaris/docs$ gitbook current
GitBook version is 3.2.2
kc5tja@enif:~/git/polaris/docs$ _
```

My work-around is to just run it in an infinite while loop in Bash.  This happens almost constantly for me.  :(

**Comment by mlidbom** [comment] 2016-10-27 12:46
Same here with gitbook 3.2.2 on Windows 10.
It crashes on every single file update.
Works without a hitch with 2.6.7

**Comment by mlidbom** [comment] 2016-10-27 12:49
Same problem as #1379 ?

**Comment by mlidbom** [comment] 2016-10-27 13:03
I have a branch on a public repository where I see this problem every time any file is updated:  https://github.com/mlidbom/AsciiDocScratch/tree/gitbook-serve-bug-repro

Hope this might help with tracking down the problem.

**Comment by zekedroid** [comment] 2016-11-02 16:51
Same problem, fails on our jenkins boxes. Randomly fails to find certain assets, not always the same one. Sometimes works fine. Seems to be some kind of race condition on reading the assets files.

**Comment by zekedroid** [comment] 2016-11-22 18:48
Update:

Seems like our team might have found an empirically proven cause, but not with enough detail to diagnose. We found that increasing the memory of our servers solves the issue after realizing that there was an out of memory error being thrown.

It seems gitbook is a memory hog and will crash sometimes, depending on the size of the book.

Will continue to debug but maybe this helps someone find the true source of the issue

**Comment by cclehui** [comment] 2016-11-25 13:20
CLI version: 2.3.0
GitBook version: 3.2.2
node : v6.2.0
npm : 3.8.9

info: 7 plugins are installed
info: 6 explicitly listed
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 4 pages
info: found 2 asset files

Error: ENOENT: no such file or directory, stat 'E:\gitbook\babytree\_book\gitbook\gitbook-plugin-fontsettings\fontsettings.js',Error: ENOENT: no such file or directory, stat 'E:\gitbook\babytree\_book\gitbook\gitbook-plugin-fontsettings\website.css'

**Comment by Simran-B** [comment] 2016-11-25 16:07
Randomly fails for me on Windows 10:

> info: found 4 asset files
>
> Error: ENOENT: no such file or directory, stat 'C:\Users\Simran\support\gitbook-experiments\_book\gitbook\gitbook-plugin-lunr\lunr.min.js'

CLI version: 2.3.0
GitBook version: 3.2.2
Node: v6.7.0

**Comment by eugene-goroschenya** [comment] 2016-12-15 12:37
+1 fails quite often, Windows 7

**Comment by zhilidali** [comment] 2016-12-15 13:12
Are you random mistakes? How I have been wrong?After the system and the environment has also been wrong

**Comment by arjun27** [comment] 2016-12-17 08:39
I was able to reduce these errors significantly after doing a fresh git clone. I'm on macOS Sierra though.

**Comment by hfxu** [comment] 2016-12-28 02:20
Hello @zargex ,i fount that not working too,sorry for reply too late.

**Comment by dotnetdan** [comment] 2017-01-10 18:48
I'm having this problem for both build and serve, not just intermittently, always. Running Windows 7 64 bit. 

```
mkdir testbook
cd testbook
gitbook init
gitbook serve ./ --log=debug --debug

Live reload server started on port: 35729
Press CTRL+C to quit ...

debug: readme found at README.md
debug: summary file found at SUMMARY.md
debug: cleanup folder "c:\Development\Source\gitbook\_book"
info: 7 plugins are installed
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 1 pages
info: found 0 asset files
debug: calling hook "config"
debug: calling hook "init"
debug: copy assets from theme C:\Users\dotnetdan\.gitbook\versions\3.2.2\node_modules\gitbook-plugin-theme-default\_assets\website
debug: copy resources from plugin C:\Users\dotnetdan\.gitbook\versions\3.2.2\node_modules\gitbook-plugin-fontsettings\assets

Error: ENOENT: no such file or directory, stat 'c:\Development\Source\gitbook\_book\gitbook\gitbook-plugin-fontsettings\fontsettings.js'
```

The missing `fontsettings.js` is there, but empty: 

![image](https://cloud.githubusercontent.com/assets/500965/21819815/3b66b17a-d73b-11e6-8cb4-f3771e391d99.png)


I manually copied it from ~\.gitbook\versions\3.2.2\node_modules\gitbook-plugin-fontsettings\assets, but after running build or serve, it immediately gets back to 0kb and results in the same error. It looks like the build/serve commands are always dropping an empty copy of the file.

Disabling the fontsettings plugin results in the same error, for a another file.

**Comment by obogobo** [comment] 2017-01-18 20:00
After several hours of debugging, I believe I found the root problem.
You'll notice the error here is always "Error: ENOENT: no such file or directory, stat"

Dependency `cpr` of gitbook (for recursively copying directories) has an option { confirm: true }, which runs a stat on the destination directory after the copy, to make sure it was successful. 
https://www.npmjs.com/package/cpr#usage

This uses `graceful-fs.stat()` and appears to be what's swallowing the stack trace and blowing up on copying plugins in gitbook.

To fix:
Reach into `~/.gitbook/versions/3.2.2/lib/output/website/copyPluginAssets.js` and tell `cpr` (aliased as fs.copyDir) not to "confirm" ...which is what downstream invokes the stat.

It's this line, here: https://github.com/GitbookIO/gitbook/blob/3.2.2/lib/output/website/copyPluginAssets.js#L112

Rerun and see the book compile w/o error.

**Comment by FibreFoX** [comment] 2017-02-04 17:21
@obogobo I started with a fresh gitbook and called `gitbook serve` without having it being used before, I get stucked at the `buttons.js` now.  Do you have any idea how to fix that?

**Comment by zekedroid** [comment] 2017-02-04 17:59
@FibreFoX we're waiting to see if that PR gets approved as from our testing that is what breaks in some systems (given the compatibility issue of the `stat` command ran by the `confirm` property on the file copying step). We resorted to using the forked version of @obogobo until the gitbook contributors approve the PR or fix it in another way.

Ironic that the error handling is what causes the error :P

**Comment by ctron** [comment] 2017-03-29 08:57
Is there any plan on fixing this? This does not only affect `gitbook serve` but also `gitbook build`.

**Comment by mistory** [comment] 2017-04-25 17:02
I had same error on win7.
CLI version: 2.3.0
GitBook version: 3.0.2
node version: 4.4.4

**Comment by FibreFoX** [comment] 2017-04-25 18:12
@zekedroid Is there any ETA for this bug being fixed? It is kinda depressing seeing this not being worked on :(

(or maybe this is already fixed with different changes?)

**Comment by zekedroid** [comment] 2017-04-25 18:51
The PR is made but no one has looked at it so it's the waiting game for now
or fork the repo and make the changes locally.

**Comment by x2yline** [comment] 2017-05-29 02:14
I had same error on win7.
But when I **close the antivirus software** "360 Total Security", this error was eliminated,
Hope this might help you.

**Comment by dailc** [comment] 2017-06-28 03:30
@obogobo  thanks!

supplement:

for example `C:\Users\Administrator\.gitbook\versions\3.2.2\lib\output\website\copyPluginAssets.js`

instead of `xxx\Administrator\AppData\Roaming\npm\node_modules\gitbook\xxx`

**Comment by aleen42** [comment] 2017-08-03 16:21
Awesome!!!

**Comment by yudong-yang** [comment] 2017-08-24 09:57
I get the same error

Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 7 plugins are installed
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 27 pages
info: found 47 asset files

Error: ENOENT: no such file or directory, stat 'E:\git-repo\duiba_api_doc\_book\
gitbook\gitbook-plugin-fontsettings\website.css',Error: ENOENT: no such file or
directory, stat 'E:\git-repo\duiba_api_doc\_book\gitbook\gitbook-plugin-fontsett
ings\fontsettings.js'

**Comment by bluedusk** [comment] 2017-08-30 08:35
same issue on:
 - win7
 - gitbook 3.2.3
 - node 7.10.1

@obogobo This really worked for me ! Many Thanks. Cant believe this issue still open over a year.

```
        assetOutputFolder,
        {
            deleteFirst: false,
            overwrite: true,
            confirm: false
        }

```

**Comment by willin** [comment] 2017-09-22 01:25
```
gitbook serve
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 10 plugins are installed
info: loading plugin "donate"... OK
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "hints"... OK
info: loading plugin "headings"... OK
info: loading plugin "copy-code"... OK
info: loading plugin "theme-default"... OK
info: found 19 pages
info: found 33 asset files

Error: ENOENT: no such file or directory, open '/Users/willin/.gitbook/versions/4.0.0-alpha.6/node_modules/gitbook-plugin-livereload/_assets/plugin.js'
```

- node v8.5.0
- os x 10.13.0

**Comment by ouweiya** [comment] 2017-09-22 14:21
My computer is back to normal after reboot！

**Comment by ctron** [comment] 2017-09-25 07:45
Unfortunately this problem cannot be solved by rebooting.
> My computer is back to normal after reboot！
> Try to reboot and maybe solve the problem!

**Comment by ouweiya** [comment] 2017-09-26 17:33
#### After a few days of trying, I finally solved this problem!

You only need to reduce the version number and node.js version to solve the problem of failure to start and refresh the interrupt.

**I did a lot of testing and found that the previous version of 3.0.0 did not have these problems, and node.js was V6.**
It can be solved.

**I recommend using: 2.6.7 ~ 2.6.4**

You add a line in `book.json`:


```json
{
    "gitbook" : "2.6.7"
}
```

Node.js： V6

```
$ node -v
v6.11.3
```
**then**

install：

```
$ gitbook install
```

run:

```
gitbook serve
```

I tested the version:

Recommended: `2.6.7 ~ 2.6.4`

```
$ gitbook ls 
GitBook Versions Installed:
      3.2.3
      3.1.1
      3.1.0
      3.0.3
      3.0.0
      2.6.7
      2.6.6
      2.6.4
      2.3.2
      2.1.0
```

I am not a javascript expert, I can only use this stupid method to solve the problem, I sincerely hope to help you!

**Comment by Carson126** [comment] 2017-10-12 04:44
I get the same error. I have few times(less than 0.1%) works well after run as administrator and 
 `npm cache clean`
 I've tried gitbook version 2.6.7. it seems work well and cannot be using the graceful-fs module.
how to use gitbook 3.x.x for win10. thanks alot

**Comment by obogobo** [comment] 2017-10-12 13:26
Scroll up 😉

**Comment by aheroaa** [comment] 2017-11-09 01:41
In windows use administrator then run the command, you will resolve the issue.

**Comment by adamlesniak** [comment] 2017-11-29 12:03
In my case installing ``gitbook`` as a package in the actual project folder was the solution.

This error was appearing when using ``gitbook-cli``

**Comment by jppampin** [comment] 2017-12-26 18:26
Thank you @bluedusk!! Your tip works like a charm.
OS: Win7
GitBook version is 3.2.3
Nodejs: v8.9.1

Steps:
1. Edit file: *C:\Users\[user]\.gitbook\versions\3.2.3\lib\output\website\copyPluginAssets.js*
2. Modify in two places *copyAssets(output, plugin)* and *copyResources(output, plugin)*, the line:
```
            confirm: true
```
by
```
            confirm: false
```

**Comment by daniele-orlando** [comment] 2018-01-15 14:58
Same error but on MacOS and **symbolic links**.

**Comment by liuzhenrain** [comment] 2018-06-13 09:10
@obogobo thank you....

**Comment by zxflslzyx** [comment] 2018-07-06 02:52
same issue

**Comment by zxflslzyx** [comment] 2018-07-06 02:54
node  8 + , npm 4+ ,gitbook 3.2.3 ,they seems to be  lastest,but this problem still appear to my env.

**Comment by zxflslzyx** [comment] 2018-07-06 02:56
can you see my problem ?sir

**Comment by flyyang** [comment] 2018-07-09 08:41
any update on this, i don't want change the file manually...

**Comment by thiagocaiubi** [comment] 2018-07-11 18:45
So it's been a while and the bug is still alive. I could see some effort to close this issues within pull requests but sadly without approval. Sincerely, I stopped digging to understand why.

I came up with this simple Dockerfile as you might also want to use:

```Dockerfile
FROM node:8.11-alpine

RUN npm install --global gitbook-cli && \
    gitbook fetch 3.2.2 && \
    gitbook install && \
    npm cache clear --force && \
    rm -rf /tmp/*

# Fixes https://github.com/GitbookIO/gitbook/issues/1309
RUN sed -i.bak 's/confirm: true/confirm: false/g' \
    /root/.gitbook/versions/3.2.2/lib/output/website/copyPluginAssets.js
```

Build the image:

```console
$ docker build . -t gitbook
```

Write README.md example:

```console
$ echo "# Hello Gitbook" > README.md
```

Build a book:

```console
$ docker run -v $(pwd):/gitbook -w /gitbook --rm -it gitbook build . output
```

**Comment by flyyang** [comment] 2018-07-13 04:16
Seems the code was merged, when a new release will be published?

**Comment by Simran-B** [comment] 2018-07-13 10:11
The official repository is dead.

**Comment by sam-falvo** [comment] 2018-07-13 15:15
Sure seems that way.  The commercial website indicates that they're on Gitbook v2 as of February 2018, which means, despite the semantic versioning of this package, this is all under the Gitbook v1 umbrella.

Guess it's time to move on to other tools.  Back to LaTeX2html, I guess.  ;-P

**Comment by lzhou1110** [comment] 2018-10-18 22:30
Checked out the latest beta version solved this issue for me.

Use the below command to list all available versions:
`gitbook ls-remote`

Then I installed pre-release 4.0.0-alpha.6
`gitbook fetch 4.0.0-alpha.6`

See the GitHub repo for more details:
https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md

**Comment by Simran-B** [comment] 2018-11-20 13:06
@15766273878 It can occur randomly any time again. I doubt rebooting is a permanent solution for anything, ever.

**Comment by LawEric** [comment] 2018-12-27 07:36
Sadly，I get the same error.

- win 10

- gitbook 3.2.3

- node 10.14.1

Error: ENOENT: no such file or directory, stat 'F:\cmp2.0\doc\blueking\_book\gitbook\gitbook-plugin-toggle-chapters\toggle.css'

**Comment by aallbrig** [comment] 2019-01-28 15:23
@thiagocaiubi Thanks! I added...

```
# Fixes https://github.com/GitbookIO/gitbook/issues/1309
RUN sed -i.bak 's/confirm: true/confirm: false/g' \
    /root/.gitbook/versions/3.2.2/lib/output/website/copyPluginAssets.js
```

... to my `Dockerfile` and all works great now.

---
@Simran-B (@sam-falvo ?) Do you know why gitbook decided to deprecate gitbook-cli?

**Comment by rafecolton** [comment] 2019-02-08 21:18
I am getting this error too.

@lzhou1110 I did this and it immediately failed on the next rebuild.

**Comment by aleung** [comment] 2019-03-25 06:21
My fork `@aleung/gitbook` implemented the fix: https://github.com/aleung/gitbook

**Comment by cyanTao** [comment] 2024-03-25 09:54
我已收到您的来信，谢谢。

**Closed** 2024-03-25 09:53 UTC
Labels: bug, 3.0.0, investigating
