### ISSUE TITLE
HTML rendering jank / stutter

### ISSUE THREAD

**Issue by scragg0x** [GitbookIO/gitbook#840] opened 2015-07-30 13:44 UTC
I created my gitbook and it's a fair size with about 500 pages.  After each page load the site is rendered briefly without style then the style gets applied.  I am just using default theme btw.  This creates a bad transition between pages.  I haven't dived in too deep in the code to find out the cause.  Is gitbook applying the theme/styles via javascript?  I also notice my search_index.json is 11M and it gets loaded on every page load.  Although this is cached and asynchronous which shouldn't block, it may be keeping my CPU busy enough to delay other aspects of page load.

**Comment by gaearon** [comment] 2015-08-06 15:25
Seems like a duplicate of https://github.com/GitbookIO/gitbook/issues/838.

**Comment by AaronO** [comment] 2015-08-07 14:58
Fixed by #847

**Closed by AaronO** 2015-08-07 14:58 UTC
