### ISSUE TITLE
error using gitbook build

### ISSUE THREAD

**Issue by gustavomr** [GitbookIO/gitbook#1822] opened 2017-07-14 12:46 UTC
gitbook build or gitbook init

Error loading version latest: Error: Cannot find module 'is'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/09893064708/.gitbook/versions/3.2.2/lib/modifiers/summary/insertArticle.js:1:72)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

TypeError: Cannot read property 'commands' of null

Enviroment:
CLI version: 2.3.1
GitBook version: 3.2.2
Node version v7.5.0

**Comment by AaronO** [comment] 2017-07-14 12:56
Closing as a duplicate of https://github.com/GitbookIO/gitbook-cli/issues/68, should be fixed by the `gitbook-cli@2.3.2` release.

**Closed by AaronO** 2017-07-14 12:56 UTC
