### ISSUE TITLE
warning message after updating to Node.js v6

### ISSUE THREAD

**Issue by yyqian** [GitbookIO/gitbook#1255] opened 2016-04-27 05:38 UTC
Warning message:

```
➜ gitbook init
(node:24891) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:24891) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

**Comment by Blarfursnarg** [comment] 2016-05-03 12:30
Same issue for me.
Also, `gitbook pdf` now gives the error: 
`TypeError: Path must be a string. Received undefined`
which might be related somehow.

**Comment by spudly** [comment] 2016-05-05 18:12
I think the problem is probably that the chokidar dependency is out of date. Bump that and you'll get bug fixes in the fsevents module that take care of this.

**Comment by SamyPesse** [comment] 2016-05-06 22:25
This is fixed in version `3.0.0`. We've also added Node 6 to the travis Node matrix.

I'm closing this issue.

**Closed by SamyPesse** 2016-05-06 22:25 UTC
Labels: 3.0.0, bug

**Comment by mattlqx** [comment] 2016-05-25 19:21
I'm getting this issue now when Travis builds my book. Build #bdc8336999 is an example.

**Comment by sophieyoung717** [comment] 2016-06-03 01:29
I try to update gitbook to 3.0.0, which gives me error:

gitbook update
Installing GitBook 3.0.3
module.js:442
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/folders/bp/v4tv90x51zgbtcsr7std_7tc0000gn/T/tmp-17546AO72BUvEdj1P/node_modules/gitbook/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:14:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Failed to execute '/usr/local/bin/node /private/var/folders/bp/v4tv90x51zgbtcsr7std_7tc0000gn/T/tmp-17546AO72BUvEdj1P/node_modules/gitbook/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
gitbook@3.0.3 ../../../../../../../var/folders/bp/v4tv90x51zgbtcsr7std_7tc0000gn/T/tmp-17546AO72BUvEdj1P/node_modules/gitbook
├── escape-string-regexp@1.0.5
├── escape-html@1.0.3
├── destroy@1.0.4
├── bash-color@0.0.4
├── ignore@3.1.2
├── gitbook-plugin-livereload@0.0.1
├── cp@0.2.0
├── nunjucks-do@1.0.0
├── graceful-fs@4.1.4
├── github-slugid@1.0.1
├── direction@0.1.5
├── spawn-cmd@0.0.2
├── gitbook-plugin-fontsettings@1.0.3
├── is@3.1.0
├── q@1.4.1
├── object-path@0.9.2
├── extend@3.0.0
├── json-schema-defaults@0.1.1
├── gitbook-plugin-search@2.2.1
├── jsonschema@1.1.0
├── crc@3.4.0
├── urijs@1.18.0
├── semver@5.1.0
├── immutable@3.8.1
├── dom-serializer@0.1.0 (domelementtype@1.1.3, entities@1.1.1)
├── omit-keys@0.1.0 (isobject@0.2.0, array-difference@0.0.1)
├── error@7.0.2 (string-template@0.2.1, xtend@4.0.1)
├── tmp@0.0.28 (os-tmpdir@1.0.1)
├── npmi@2.0.1 (semver@4.3.6)
├── merge-defaults@0.2.1 (lodash@2.4.2)
├── send@0.13.2 (range-parser@1.0.3, etag@1.7.0, statuses@1.2.1, ms@0.7.1, fresh@0.3.0, mime@1.3.4, depd@1.1.0, debug@2.2.0, http-errors@1.3.1, on-finished@2.3.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rmdir@1.2.0 (node.flow@1.2.3)
├── resolve@1.1.7
├── cpr@1.1.1 (rimraf@2.4.5)
├── fresh-require@1.0.3 (is-require@0.0.1, shallow-copy@0.0.1, sleuth@0.1.1, astw@1.3.0, through2@0.6.5, acorn@0.9.0, escodegen@1.8.0)
├── tiny-lr@0.2.1 (parseurl@1.3.1, livereload-js@2.2.2, qs@5.1.0, debug@2.2.0, body-parser@1.14.2, faye-websocket@0.10.0)
├── gitbook-plugin-theme-default@1.0.3
├── nunjucks@2.4.2 (asap@2.0.4, yargs@3.32.0)
├── front-matter@2.0.8 (js-yaml@3.6.1)
├── request@2.72.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── read-installed@4.0.3 (debuglog@1.0.1, util-extend@1.0.3, slide@1.1.6, readdir-scoped-modules@1.0.2, read-package-json@2.0.4)
├── gitbook-plugin-lunr@1.1.0 (lunr@0.5.12)
├── gitbook-plugin-highlight@2.0.2 (highlight.js@9.2.0)
├── moment@2.13.0
├── i18n-t@1.0.0 (lodash@3.10.1)
├── gitbook-plugin-sharing@1.0.2 (lodash@3.10.1)
├── gitbook-asciidoc@1.1.4 (gitbook-html@1.1.0, asciidoctor.js@1.5.5-1, lodash@3.10.1)
├── gitbook-markdown@1.2.3 (kramed-text-renderer@0.2.1, gitbook-html@1.2.1, kramed@0.5.6, lodash@3.10.1)
├── juice@1.11.0 (util-deprecate@1.0.2, deep-extend@0.4.1, slick@1.12.2, batch@0.5.3, commander@2.9.0, cssom@0.3.0, cross-spawn-async@2.2.4, cheerio@0.19.0, web-resource-inliner@1.2.1)
├── cheerio@0.20.0 (entities@1.1.1, css-select@1.2.0, htmlparser2@3.8.3, jsdom@7.2.2, lodash@4.13.1)
├── chokidar@1.5.0 (path-is-absolute@1.0.0, inherits@2.0.1, glob-parent@2.0.0, async-each@1.0.0, is-glob@2.0.1, is-binary-path@1.0.1, readdirp@2.0.0, anymatch@1.3.0)
└── npm@3.9.2


**And gitbook pdf still does not work**

**Comment by AlJohri** [comment] 2016-06-15 15:26
I got the following stacktrace.

```
➜   thing [master] ⚡ gitbook build
Installing GitBook 3.1.1
module.js:442
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/folders/wc/5cw9h18x48z9h4dwfk1tk7n5jhnlj6/T/tmp-1221364ie26zCT6r3/node_modules/gitbook/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:14:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Failed to execute '/usr/local/Cellar/node/6.2.0/bin/node /private/var/folders/wc/5cw9h18x48z9h4dwfk1tk7n5jhnlj6/T/tmp-1221364ie26zCT6r3/node_modules/gitbook/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
gitbook@3.1.1 ../../../../../../var/folders/wc/5cw9h18x48z9h4dwfk1tk7n5jhnlj6/T/tmp-1221364ie26zCT6r3/node_modules/gitbook
├── escape-html@1.0.3
├── escape-string-regexp@1.0.5
├── destroy@1.0.4
├── bash-color@0.0.4
├── ignore@3.1.2
├── graceful-fs@4.1.4
├── q@1.4.1
├── gitbook-plugin-livereload@0.0.1
├── cp@0.2.0
├── nunjucks-do@1.0.0
├── github-slugid@1.0.1
├── direction@0.1.5
├── spawn-cmd@0.0.2
├── gitbook-plugin-fontsettings@2.0.0
├── is@3.1.0
├── extend@3.0.0
├── object-path@0.9.2
├── json-schema-defaults@0.1.1
├── gitbook-plugin-search@2.2.1
├── jsonschema@1.1.0
├── semver@5.1.0
├── crc@3.4.0
├── urijs@1.18.0
├── immutable@3.8.1
├── front-matter@2.1.0
├── dom-serializer@0.1.0 (domelementtype@1.1.3, entities@1.1.1)
├── omit-keys@0.1.0 (array-difference@0.0.1, isobject@0.2.0)
├── error@7.0.2 (string-template@0.2.1, xtend@4.0.1)
├── tmp@0.0.28 (os-tmpdir@1.0.1)
├── npmi@2.0.1 (semver@4.3.6)
├── send@0.13.2 (etag@1.7.0, fresh@0.3.0, statuses@1.2.1, range-parser@1.0.3, ms@0.7.1, depd@1.1.0, debug@2.2.0, mime@1.3.4, on-finished@2.3.0, http-errors@1.3.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rmdir@1.2.0 (node.flow@1.2.3)
├── resolve@1.1.7
├── cpr@1.1.1 (rimraf@2.4.5)
├── fresh-require@1.0.3 (is-require@0.0.1, shallow-copy@0.0.1, astw@1.3.0, sleuth@0.1.1, through2@0.6.5, acorn@0.9.0, escodegen@1.8.0)
├── js-yaml@3.6.1 (esprima@2.7.2, argparse@1.0.7)
├── gitbook-plugin-theme-default@1.0.4
├── tiny-lr@0.2.1 (parseurl@1.3.1, livereload-js@2.2.2, qs@5.1.0, debug@2.2.0, body-parser@1.14.2, faye-websocket@0.10.0)
├── nunjucks@2.4.2 (asap@2.0.4, yargs@3.32.0)
├── request@2.72.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── read-installed@4.0.3 (debuglog@1.0.1, util-extend@1.0.3, slide@1.1.6, readdir-scoped-modules@1.0.2, read-package-json@2.0.4)
├── gitbook-plugin-lunr@1.1.0 (lunr@0.5.12)
├── gitbook-plugin-highlight@2.0.2 (highlight.js@9.2.0)
├── moment@2.13.0
├── gitbook-plugin-sharing@1.0.2 (lodash@3.10.1)
├── juice@2.0.0 (deep-extend@0.4.1, slick@1.12.2, batch@0.5.3, commander@2.9.0, cssom@0.3.1, cross-spawn-async@2.2.4, web-resource-inliner@2.0.0)
├── i18n-t@1.0.1 (lodash@4.13.1)
├── gitbook-asciidoc@1.2.2 (gitbook-html@1.3.3, asciidoctor.js@1.5.5-1, lodash@4.13.1)
├── cheerio@0.20.0 (entities@1.1.1, css-select@1.2.0, htmlparser2@3.8.3, jsdom@7.2.2, lodash@4.13.1)
├── gitbook-markdown@1.3.2 (kramed-text-renderer@0.2.1, gitbook-html@1.3.3, kramed@0.5.6, lodash@4.13.1)
├── chokidar@1.5.0 (path-is-absolute@1.0.0, inherits@2.0.1, glob-parent@2.0.0, async-each@1.0.0, is-glob@2.0.1, is-binary-path@1.0.1, readdirp@2.0.0, anymatch@1.3.0)
└── npm@3.9.2
warn: no summary file in this book
info: 7 plugins are installed
info: 6 explicitly listed
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 1 pages
info: found 253 asset files
info: >> generation finished with success in 3.9s !
```
`gitbook build` and `gitbook serve` work for me despite the error

**Comment by OlegZavrazhin** [comment] 2016-06-21 12:27
The same issue:

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'escape-string-regexp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Oleg\Desktop\проекты\empty-project\node_modules\gulp\node_modules\chalk\index.js:2:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

```
