### ISSUE TITLE
Ability to set path in `book.json` structure

### ISSUE THREAD

**Issue by urosjarc** [GitbookIO/gitbook#1601] opened 2016-11-18 10:43 UTC
I want to put path in book.json structure object, but it fails...
```
ConfigurationError: Error with book's configuration: config.structure.readme does not match pattern "^[a-zA-Z-._d,s]+$"
```

Pls fix this...

**Comment by simonkberg** [comment] 2016-11-22 17:23
This is a duplicate of #1244

**Closed** 2024-03-25 09:50 UTC
