### ISSUE TITLE
<div> with "style" specified breaks online editor

### ISSUE THREAD

**Issue by hawkhero** [GitbookIO/gitbook#835] opened 2015-07-27 02:32 UTC
# Steps to reproduce
1. enter <div style="text-align:center"></div>

# The result I saw

The preivew area shows error message below:
> Invarriant Violation: The 'style' prop expectes a mapping from style properties to values, not a string. For example...

**Comment by ThomWright** [comment] 2015-07-28 10:38
Dupe of #824?

**Comment by AaronO** [comment] 2015-07-28 10:40
@hawkhero @ThomWright Yes, this is a duplicate. Closing this in favor of #824 which we should fix/change (and when fixed will fix your issue).

**Closed by AaronO** 2015-07-28 10:40 UTC
