### ISSUE TITLE
Add an option to specify config file

### ISSUE THREAD

**Issue by typhonius** [GitbookIO/gitbook#753] opened 2015-05-20 00:53 UTC
I'd like a way to specify a particular book.json to use from within a repository. The usecase being that many different snippets can be used to generate different combinations of books and each combination would require different variables from the book.json.

I note that over [here](http://coffeedoc.info/github/GitBookIO/gitbook/master/) there's a config option:

```
--config <config file>    Configuration file to use, defaults to book.js or book.json
```

although that doesn't seem to work for the latest version of gitbook-cli.

**Comment by kylebrowning** [comment] 2015-05-21 02:34
+1

**Comment by juaalta** [comment] 2015-05-21 07:54
+1

**Comment by friedger** [comment] 2015-05-21 08:08
Do you want to publish one book with several sub-books like for multi languages (see
http://gitbookio.gitbooks.io/progit/content/) or do you want to have different books on gitbook.io and just use the same repository with a different config (BTW, it is fixed in here: https://github.com/GitbookIO/gitbook/blob/12c06b384f4fcf69c1b283b924d8823c23737972/lib/configuration.js#L112)?

If the latter, this would only work when the book is hooked to an external repo because one book is one gitbook repo. So, there would be serveral gitbooks and just one external repo. 
For this, the website should probably provide an edit field in settings/publication.

**Comment by kylebrowning** [comment] 2015-05-21 15:15
Personally I'm not trying to get these books up on gitbook.io.

The idea here is we have many different book.json's that house different configurations of each book. Maybe some with different margins, maybe some we a different summary.md, maybe some with different header templates. 

We have to blow away book.son and regain a book each time we want to do this. Would be nice to just cd into a dir with book.json and build

Maybe @typhonius can elaborate more.

**Comment by typhonius** [comment] 2015-05-21 22:23
Similar to @kylebrowning, I'm not looking to make these publicly accessible on gitbook.io. Rather, I'll have a library of snippets (each using variables provided by a book.json) and a directory of SUMMARY.md files from which to construct different combinations of gitbooks.

My directory structure currently is like this:

```
.
├── books
│   ├── book_one
│   │   ├── book.json
│   │   ├──SUMMARY.md
│   │   ├── custom.md
│   ├── book_two
│   │   ├── book.json
│   │   ├──SUMMARY.md
│   │   ├── custom.md
├── cover.md
├── snippets
│   ├── dragon_taming.md
│   ├── sword_swallowing.md
│   ├── axe_grinding.md
```

Each book directory comes with a custom book.json and SUMMARY.md that feed off the snippets in the snippets directory. When I need to build a book, I copy the book.json and SUMMARY.md from the book specific directory into the root directory and build from there.

If the commit mentioned above would allow me to specify a book.json on the command line, then I can specify a SUMMARY.md in the book.json and would be well.

**Comment by kylebrowning** [comment] 2015-05-27 16:47
@friedger Is this possible?

**Comment by friedger** [comment] 2015-05-29 08:17
I guess something like https://github.com/GitbookIO/gitbook/pull/773 should do the trick. But I am not the gitbook expert to judge this :-) Maybe @SamyPesse ?

**Comment by kylebrowning** [comment] 2015-06-05 17:49
#789 as well

**Comment by SamyPesse** [comment] 2015-06-05 19:08
Sorry, I'm really busy with the new version of the webeditor.

I'm going to take a look at your PRs this weekend.

BTW: we'll need to also make a change in `gitbook-cli` (reading the book.json to choose the gitbook version).

**Comment by kylebrowning** [comment] 2015-06-05 20:09
@SamyPesse Thanks for taking a look, would love to see this in gitbook-cli.

Where is the code for gitbook-cli located?

**Comment by SamyPesse** [comment] 2015-06-05 20:54
https://github.com/GitbookIO/gitbook-cli

**Comment by kylebrowning** [comment] 2015-06-05 21:49
@SamyPesse I might be a bit confused, whats the difference between gitbook, and gitbook-cli?

**Comment by AaronO** [comment] 2015-06-05 22:05
@kylebrowning This repo (`gitbook`) contains the main code as a library, and `gitbook-cli` contains the command line executable.

They were separated so people could install older versions (rather that have one global version of gitbook) to be compatible with books that had breaking changes caused by newer versions.

Essentially it allows users to have multiple versions rather than only one.

**Comment by AaronO** [comment] 2015-06-05 22:26
@kylebrowning I think it can indeed be confusing for people that don't care about the version aspect (which is probably a minority).

**Comment by kylebrowning** [comment] 2015-06-05 22:37
@AaronO Makes sense, I'm not sure I see where I can add the options to do config in gitbook-cli though. :/

**Comment by kylebrowning** [comment] 2015-06-06 17:18
I think this might need to be something someone else takes on.

It looks like gitbook-cli installs gitbook, I can't get it to install my local checkout with npm link.

That being said it looks like gitbook-cli just runs commands against the gitbook app.

Maybe I'm missing something, but the PR's linked, (#789) add this config file option to gitbook, and that in turn will show up in gitbook-cli.

Thoughts, @AaronO @SamyPesse ?

**Comment by friedger** [comment] 2015-06-06 20:48
https://github.com/GitbookIO/gitbook-cli/blob/master/lib/versions.js#L195

In cli it is hardcoded where to lookup some configs

**Comment by AaronO** [comment] 2015-06-07 00:12
@friedger That's used to lookup a specific `gitbook` version (if specified by the user).

What would need to happen to get this work is add a `cli` flag in `gitbook-cli`, use that to specify the file to read the version (from).

Then the important part, pass that down to the `Book` and `Configuration` classes here in `gitbook`, respectively in `lib/book.js` and `lib/configuration.js`.

The `book.json` is loaded in `Configuration.load`, more specifically it's path is computed here: https://github.com/GitbookIO/gitbook/blob/master/lib/configuration.js#L102-L104

So what needs to be done:

1. Add a `--config` flag in `gitbook-cli` (default to `book.json`).
    a. Use that to read the version while we're at it
2. Pass that to the `gitbook` library
3. Pass that to the `Book` class
4. Pass that to the `Configuration` class that will then dynamically compute the path prior to loading in `Configuration.load`

That shouldn't be too hard to implement but requires some time attention to detail and testing.

**Comment by SamyPesse** [comment] 2015-06-08 19:20
After some reflexion,  here is a simple solution that already works with current gitbook versions:

Instead of creating a `book.json`, you can create a `book.js`, for example:

```js
if (process.env.TEST1) {
      module.exports = require('./book.test.json')
} else {
      module.exports = {
            title: "Test 2"
      };
}
```

and then easily run:

```
TEST1=true gitbook serve
```

**Comment by kylebrowning** [comment] 2015-06-08 19:30
Thats very interesting. It would be nice to to define this in a json file, but this at least unblocks me!

Thanks @SamyPesse

**Comment by SamyPesse** [comment] 2015-06-08 19:32
You can use the `book.js` to require different `.json` files in a `config` folder.

**Comment by kylebrowning** [comment] 2015-06-08 19:35
Was just thinking that.

Ill post what I come up with for anyone else to use.

**Comment by kylebrowning** [comment] 2015-06-08 21:31
This works great actually! Thanks for the insight.

    if (process.env.config) {
	  var custom_folder = process.env.var1;
	  var custom_folder2 = process.env.var2;
	  
      module.exports = require('./subfolder/' + var1 + '/' + var2 + '/book.json')
    }
```

**Comment by Simran-B** [comment] 2016-11-26 18:16
If I want to use a book.json file, but dynamically set certain properties using a book.js script, is the following a good pattern?

```
var fs = require('fs');

var config;
try {
    config = require('./book.json');
} catch(err) {
    config = {}
}

var version;
try {
    version = fs.readFileSync('./VERSION', 'utf8'); 
} catch(err) {
    version = 'n/a';
}
config.version = version;

module.exports = config;
```

Note that fs.readSync (so async with a callback) does not seem to be supported, the operations must be synchronous.

**Closed** 2024-03-25 09:57 UTC
