### ISSUE TITLE
multiple glossary term, same definition

### ISSUE THREAD

**Issue by nagim** [GitbookIO/gitbook#1231] opened 2016-04-15 08:05 UTC
Hi,

Is it possible to assign multiple glossary term to one definition?
Like this:

``` markdown
# term1, term2

Definition for term1 and term 2
```

Also, glossary is not case sensitive now (now if I have a term "IN", all "in" words are indexed and highlighted).

Thanks,
Imre

**Comment by DavidMGross** [comment] 2016-05-15 22:16
See also #969.

I agree this would be useful.

**Comment by SamyPesse** [comment] 2016-05-24 08:42
I agree "multiple glossary term for one definition" could be a nice addition.

I'll add to our roadmap for future `3.x.x` releases.

Case sensitive may be a more tricky question, it's useful to have highlighting of "hello" for the first word of a sentence for example.

**Comment by nagim** [comment] 2016-05-24 08:56
Thanks @SamyPesse.
Also, mulitple definition for one term (overloading) is even more important.

For case sensitivity, it would be enough if it would be insensitive by default, and use some config/setting to make some specific terms sensitive (because this usually concerns ~5% of the terms, but that 5% is very annoying).

**Comment by mjrussell** [comment] 2016-08-23 05:08
This seems like a must have feature in order to use the glossary.

I think that terms should be case sensitive by default, and you can enable case insensitivity by simply adding the uppercase/lower case variations to the term matching.

It would be nice to be able to define the "matchers" as well as the display name separately, enabling a single term for plural forms as well.

So you could do something like:
```
# Foo
## foo, Foo, foos, Foos

A sample name for absolutely anything, especially programs and files 
```

Not sure if the H1/H2 is the best way to configure it, could also use JSON syntax.

**Comment by ayush** [comment] 2016-11-03 21:37
@SamyPesse any outlook on this? We'd love to have `# term1, term2` so that plurals of terms are linked as well.

**Comment by NicolasRouquette** [comment] 2017-02-09 00:40
+1 this seems to be a duplicate of #969

**Comment by thomas-worm-datev** [comment] 2017-11-14 05:50
+1 Multiple Termins would be useful.
+1 need for plural feature.

**Closed** 2024-03-25 09:54 UTC
Labels: enhancement, question
