### ISSUE TITLE
Importing local files doesn't work

### ISSUE THREAD

**Issue by enzolutions** [GitbookIO/gitbook#1478] opened 2016-08-02 18:31 UTC
### What is the current behavior?

After updating the book https://github.com/hechoendrupal/drupal-console-book/tree/master/en, the import for a local file stop working

You could review the include in raw file

```
* [Available commands](commands/available-commands.md)
  {% include "./commands/available-commands-list.md" %}
```

https://raw.githubusercontent.com/hechoendrupal/drupal-console-book/master/en/SUMMARY.md
### What is the expected behavior?

Include the local file according to documentation https://toolchain.gitbook.com/templating/conrefs.html

But if you review the output at http://docs.drupalconsole.com/en/commands/available-commands.html the files weren't included and the link point to MD files instead to HTML

To check te expected result, you could check a previous build with same summary file at http://docs.drupalconsole.com/v/c5041cb44f66d17e9d9d705c2f46df3a494a1d6f/en/commands/available-commands.html

**Comment by enzolutions** [comment] 2016-08-03 03:02
After review and test a lot of option I found gitbook now has a new version released about 3 months ago 3.x

Using the book.json I could define that I want to use a old version, and now the include work , again, as you can see below

```
{
  "gitbook": "2.6.7"
}
```

But to be honest, I don't understand why the new version doesn't accept *include* if the documentation said is an accepted structure

**Comment by mblakele** [comment] 2016-12-06 22:50
related: #1504

**Comment by maxkoryukov** [comment] 2017-02-19 12:39
I think it is not related, but it is a duplicate of #1504

**Closed** 2024-03-25 09:51 UTC
