### ISSUE TITLE
Failed webhook addition / unable to access the editor

### ISSUE THREAD

**Issue by saulpandelakis** [GitbookIO/gitbook#1498] opened 2016-08-22 17:04 UTC
I have a gitbook project at this address : 
https://www.gitbook.com/book/piapandelakis/these-heroisme/details
https://piapandelakis.gitbooks.io/these-heroisme/content/

I tried to connect it to this repo : 
https://github.com/piapandelakis/these-en-ligne
But it didn't work the way I thought it would (I thought the contents of the book would be saved to the repo). I canceled everything, erased the webhook, but later I was unable to access the web editor and got this message "Error loading your book, unexpected error occured when trying to load your book: Branch "undefined" doesn't exist".

Thinking it was connected to the webhook situation, I tried : 
- adding the webhook again, but Gitbook fails to recognize the hook (I might be doing something wrong)
- disconnecting the book from the repo, but later learned in forums it didn't work in later gitbook versions)
- erasing the repo (unreasonable and extreme choice, I know)
- recreating the repo
- re-creating the hook

Nothing is working and I have no way of saving 800 pages+ of my phd dissertation...
I'll add that I do everything through the gitbook editor (I usually use the terminal, but I wanted to give a go to the editor in this case....)

any help appreciated... many thanks...
Pia

**Comment by cesards** [comment] 2016-08-23 09:18
+ 1. 

This is how I reproduce the problem:

1- I open the editor and I try to login

![screen shot 2016-08-23 at 10 17 03](https://cloud.githubusercontent.com/assets/1536079/17886675/d9c60256-691a-11e6-888f-191d3e1015d3.png)

2- Login screen appears again, so it's not login at all

![screen shot 2016-08-23 at 10 17 10](https://cloud.githubusercontent.com/assets/1536079/17886695/e5c0f43a-691a-11e6-8b0c-3773873b72e9.png)

**Comment by KINGSABRI** [comment] 2016-08-23 09:26
Same situation here

**Comment by piapandelakis** [comment] 2016-08-23 10:00
Yes Cesards, I forgot to mention that the same issue is reproduced on the desktop editor... it just loops you though the login... very frustrating. I emailed the gitbook team about it, I'll let you know what they suggest.
++

**Comment by SamyPesse** [comment] 2016-08-23 10:21
The desktop editor should work now (error has been fixed on GitBook.com).

@piapandelakisdo you still have issue with webhooks ?

**Comment by piapandelakis** [comment] 2016-08-23 11:16
Yes, the issue is still the same. This is what I get on the git side : 
<img width="1165" alt="capture d ecran 2016-08-23 a 13 09 02" src="https://cloud.githubusercontent.com/assets/7816997/17889996/6850b4f4-6933-11e6-9c09-310749f48218.png">
And this is the gitbook side : 

I guess I could upload my files to the git repo, but I'm afraid to do so because it looks like the book is "split", between what's on the repo (the readme / json files I see both ob Github and in the editor) and the actual book (still accessible online, but unavailable for edits).

I have retrieved the working files for the book, I will try to start from scratch on a new repo and see how that looks.
thanx

**Comment by cesards** [comment] 2016-08-23 11:55
It's fixed for me :-). As @SamyPesse said, the real problem was on the server, not the clients ^^. Thank you guys!! Keep working hard!

**Comment by SamyPesse** [comment] 2016-08-23 12:38
@piapandelakis even if the webhook status is not right, editing through the web-editor should edit the GitHub repository directly.

It looks like the issue is only in the webhook status check (since the webhook looks right on GitHub).

Can you try editing it with the web-editor and let me know if it trigger updates correctly? (You can clone the repository locally using GitHub to make a backup if you are worried to lost your work).

**Comment by piapandelakis** [comment] 2016-08-23 14:32
@SamyPesse : I have always tried to access the book through the web editor... I only tried the desktop app to circumvent these issues... I tried again when I got your message but still no luck (I get a view of the almost empty repo).
However, I have cloned the contents of the book and started a new project (new book, linked to a clean github repo).
thanx ! I hope the issue doesn't pop again...

**Comment by piapandelakis** [comment] 2016-08-23 14:35
@SamyPesse I have added you as a collaborator on the non-working project!
thank you

**Comment by SamyPesse** [comment] 2016-08-23 14:52
Can you grant me admin access on the repository? (otherwise I can't access the webhooks listing).

**Comment by piapandelakis** [comment] 2016-08-23 15:06
I re-added you since I didn't see any options for access rights... sorry about that. Didn't see any access rights option when adding you though...

**Comment by itdvenkat** [comment] 2017-09-15 14:19
![login window](https://user-images.githubusercontent.com/31733684/30486615-b545075e-9a4e-11e7-9a9a-8aa128c98b64.JPG)

We are seeing an issue in Gitbooks Client for Windows Version 7.0.12 where we login through Github (OAuth) through a particular user id  and even if we sign out and try to login through another user id, it gets stuck at the previous user id. We tried clearing default browser cookies but the same issue is happening. Kindly fix this issue

**Closed** 2024-03-25 09:51 UTC
Labels: bug, gitbook.com
