### ISSUE TITLE
Save settings not working

### ISSUE THREAD

**Issue by Struki84** [GitbookIO/gitbook#1572] opened 2016-10-25 06:51 UTC
I can't add, or save settings on any of my books, I'm trying to add collaborators to a book, and save requests just keeps on loading never sending the data. 

Also none of the collaborators can actually read the book.

**Comment by Struki84** [comment] 2016-10-25 06:53
Also I can't send you a ticket via your help center...

**Comment by Struki84** [comment] 2016-10-25 06:58
There is a bug in the console, witch only appears in safari 9.1, on mac os

```
[Error] TypeError: u.forEach is not a function. (In 'u.forEach(function(t,n){e[n]=t})', 'u.forEach' is undefined)
	(anonymous function) (vendor.js:11:11758)
	loadPage (vendor.js:11:11867)
	(anonymous function)
	onSubmit (vendor.js:11:13189)
	(anonymous function)
```

**Comment by AaronO** [comment] 2016-10-25 10:02
@Struki84 This issue is being fixed as we speak, it was a regression that was deployed into prod yesterday. Expect a fix to be live in the next half hour or so.

I'll close this issue, since it's a matter of time and we have our internal issue tracking this bug

**Closed by AaronO** 2016-10-25 10:02 UTC

**Comment by Struki84** [comment] 2016-10-25 10:03
Thanks! :)

**Comment by AaronO** [comment] 2016-10-25 10:05
No problem, thanks for reporting it :)

**Comment by Struki84** [comment] 2016-10-25 10:06
It's a cool tool, big system, I can sympatise 👍 :)
