### ISSUE TITLE
occasional python code block missed

### ISSUE THREAD

**Issue by DaveBackus** [GitbookIO/gitbook#924] opened 2015-09-13 13:43 UTC
This is a one-off, but it's puzzling to me.  I have lots of them, but here's one that refuses to format:  

http://davebackus.gitbooks.io/test/content/installing-python.html

Scroll down to "Run test programs" and note the code block that's printed verbatim (ie, not formatted) in the second bullet.  Even more puzzling, the GitHub md viewer renders it fine:  

http://davebackus.gitbooks.io/test/content/installing-python.html

Any suggestions?  It doesn't happen often, but when it does I'm stumped.  I can avoide it by adding a space before, but then it's not indented to align with the bulleted text,

**Comment by AaronO** [comment] 2015-09-13 14:00
Duplicate of #925

**Closed by AaronO** 2015-09-13 14:00 UTC
Labels: duplicate
