### ISSUE TITLE
Is GitBook still alive?

### ISSUE THREAD

**Issue by drobiazko** [GitbookIO/gitbook#1808] opened 2017-06-07 07:24 UTC
Is it worth to consider GitBook? I have my doubts due to:

* it seems like there is nobody reading support emails. Even as a **paying** customer I'm being ignored.
* last blog post is now 4 months old
* last commit to this repo was done more than 2 moths ago
* last tweets is almost 2 moths old
* many issues are open since months without any comments
* many pull requests are waiting to be merged since months

Any ideas?

**Comment by nagim** [comment] 2017-06-07 07:34
Hi,

Yes, it's still alive.
The lack of activity in the GitHub repo only shows that the work is currently being done in other repos that are not public.
The team is in the middle of a complete overhaul of the whole GitBook experience (that's why you didn't notice activity in the repos, as it will be a different approach compared to the existing one), which takes a lot of time and effort now. It is currently in beta testing phase, I believe.

I agree that a lack of response to support emails can be frustrating, I guess with this amount of work for a team of 5 or so people, support emails processing might be very slow.

I'm a paying customer as well and I often write to the Slack channel which often allows for speedier responses.

Cheers,
Imre

**Comment by drobiazko** [comment] 2017-06-07 08:37
Thank you for your answer @nagim. 

I understand your arguments about the new GitBook experience and the size of the team. However the guys behind GitBook need to learn how to handle customers. The only reason I purchased an organizational plan was _Individual support_. You can have the best product in the world but if you ignore your customers you will lose all of them. You just must not concentrate on delivering new version of your product without helping your paying customers.

**Comment by nagim** [comment] 2017-06-07 08:42
Yes, you're right on this.
Again, try to contact them on Slack via a direct message. That usually works best for me.

**Comment by drobiazko** [comment] 2017-06-07 08:45
I asked my questions on Slack as well. Unfortunately it was not answered either.

**Comment by nagim** [comment] 2017-06-07 08:46
The one regarding variables? If you come online, I might be able to help.

**Comment by AaronO** [comment] 2017-06-07 08:48
Hi @drobiazko,

First and foremost I am sorry if you've experienced delayed replies (could you email me at aaron@gitbook.com with the specific issues you need help with ?), I'm travelling at the moment but will get back to you when in a few hours when I'm back.

Secondly, GitBook is very much alive, we're beta testing a massive product release that solves many of the core product issues we gathered from users (by talking with users and running surveys).

I'm sorry you've encountered issues, email me or ping me on slack so I can help you with your immediate issues.

Kind Regards,
Aaron

**Comment by zuker** [comment] 2017-06-07 08:58
Hmm, it's strange to make clients struggle to get paid support...

**Comment by melvinchng** [comment] 2017-06-08 16:38
@AaronO I sent you an email regarding student discount. I have been trying to contact the team for more than a month now and I receive zero response.

**Comment by reviewher** [comment] 2017-06-12 15:50
Anyone find an alternative to gitbook?

**Comment by pnicoll** [comment] 2017-06-13 15:31
`The team is in the middle of a complete overhaul of the whole GitBook experience`

We find this troubling.

**Comment by AaronO** [comment] 2017-06-13 16:02
@pnicoll It's important to highlight that we're doing this as a result of user-feedback:
> ... product release that solves many of the core product issues we gathered from users (by talking with users and running surveys).

We spent a lot of time talking with our users, to really understand the major pain points. We've been beta-testing the new-release with a few organizations over the past few weeks with solid feedback so far.

As a result here are some of the improvements currently implemented in the new release:
- **Unified read & write experience** (much much simpler UI/UX)
- **Simple and clean company branding** out of the box (branding is super-important for public product/API docs)
    - Upload a logo and pick a color (we automatically suggest one from your logo)
    - Set custom links in header
    - Header logo & favicon
    - It takes seconds not hours (no need to write CSS/HTML/JS or plugins ...)
- **Editor now natively supports editing rich content** (hints, embeds, api methods, ...), no longer requires a templating syntax !
- Most common / popular plugin-powered features are now implemented 1st party (non-exhaustive list):
    - Title anchors
    - Collapsible TOC entries
    - Image captions
    - Hints / Callouts
    - Rich embeds (to embed external content, e.g: YouTube videos)
    - And more ...
- Relevant & **fast content-wide search** (works on users and comments too !)

Overall things are an order of magnitude simpler, more reliable and less quirky.

@pnicoll I would love to talk one-on-one over Slack or Skype/Hangouts and hear your feedback (and potential concerns).

I've had a call with @drobiazko and am working with them to help streamline their docs (they have some special requirements that no documentation solution will solve out-of-the-box).

**Comment by pnicoll** [comment] 2017-06-13 16:12
@AaronO That all sounds great, especially collapsible TOC entries (using a plug-in then clicking on a second-level TOC associated to an anchor link breaks the search entirely, which we told you about in January; see https://github.com/GitbookIO/gitbook/issues/1670, in particular @nagim 's comment `@SamyPesse this issue is quite serious, basically you cannot use search if you have scrolled down in a page, because it crashes instantly`). What worries us is what will most likely be **broken** with this overhaul.

**Comment by AaronO** [comment] 2017-06-13 17:40
@pnicoll The error you encountered is precisely a symptom of the underlaying problem that we're fixing (I'm sorry that you encountered it).

Namely that GitBook requires plugins for:
- Branding (a must-have for companies, which today have to painfully write custom HTML/CSS/...)
- Improvements (e.g: title-anchors, better search, etc ...), that should be built-in
- To include rich content (youtube videos, iframes, etc ...)
However:
- Most plugins are developed by 3rd party devs, not the core gitbook team
- Plugins may conflict with one-another (or builtin plugins, such as the crash you saw)
- They require editing `book.json` or using a templating syntax (for end-users)
- Which isn't supported by the WYSIWYG editor (it would be impossible for us to provide a tailored editing experience for arbitrary 3rd-party plugins)
- May break your builds (and prevent your content from updating ... _I hate that this is even possible_ ...)

Overall this exposes a lot of unnecessary complexity and technicalities that end-users (you guys) have to worry about, that's frustrating and a subpar UX.

The core focus of this release is building a much simpler (UI & UX) and reliable experience for our users. Everything a team needs to write their documentation should be simple, reliable and "just work"™. No build failures, plugin conflicts, sync errors, ...

I would love to jump on a call, understand your specific use-case & needs, demo you the beta so you can get a better understanding of where we're going (and see for yourself if it truly is simpler/better).

**Comment by AaronO** [comment] 2017-06-13 17:43
We will announce the beta (through an official blog post) and have a landing page with more info very soon.

We wanted to have tangible results and feedback (from beta-testers) before announcing it.

**Comment by greatdreams** [comment] 2017-06-26 03:26
Is there any latest developing information about gitbook and gitbook editor?

**Comment by FibreFoX** [comment] 2017-06-28 06:49
@AaronO  Don't want to be that picky, but how about writing some "CURRENTLY COMPLETE REWORK IN PROGRESS" inside the readme-file? This way you can communicate with non-slack users and github-only visitors.

It get's very annoying to not get response to issues like #1784, which blocks pull-requests for the current version, which makes this project seem to be dead.

**Comment by kozi** [comment] 2017-07-08 11:17
> We will announce the beta (through an official blog post) and have a landing page with more info very soon.

Can you say what **very soon** means?

**Comment by pnicoll** [comment] 2017-07-12 13:44
It's been 29 days since we've heard from @AaronO, so "very soon" seems to mean nothing.

GitBook is still billing me, however.

**Comment by AaronO** [comment] 2017-07-12 15:17
@kozi @pnicoll We'll be releasing a blog post and homepage for the new beta this week, where users will be able to request beta access (we're aiming for Friday but it might come out tomorrow, because we want to give everyone an update and showcase the new improvements and what we've been working on).

We've been working hard on the beta, you can see the release notes for the latest beta releases here: https://betadocs.gitbook.com/changelog

If you anyone has specific questions, or things they would like to see improved in GitBook (and thus tackled by this new release) I would love to jump on a quick call with them

(You can reach me at `aaron@gitbook.com`)

We've been working on this beta to solve the major key issues we heard from our users, a lot of which were non-trivial, if anyone in this thread has any issues please contact me directly.

---

I also followed up with Igor (@drobiazko) who originally started this thread, had a call with him regarding their use-case, which admittedly is a bit of an edge-case, so I explained a few approaches that would work.
Since it's unlikely that we'll implement 1st-class support for white-labelling a single project into multiple live projects, that share all their content but differ in branding and some URL rewriting.
My recommended approach was to write a small proxy service on their end that's aware of all the custom branding they want to do and uses our APIs to pull in the relevant content and rewrite it before rendering to the end-user. Allowing them to have full control over their white-labelling logic and have one simple repo of content to maintain.

**Comment by pnicoll** [comment] 2017-07-12 15:28
@AaronO Thanks for the update.

What would be really nice would be to set table column widths. Overriding with HTML (which I have to do in long cells that contain a combination of regular text and bulleted lists, for example) doesn't work, nor does forcing a column width with non-breaking spaces (&nbsp;) for tables that have the same column headers. As a result, I have tables with the same headers but different-sized columns, which makes my documentation look sloppy.

**Comment by AaronO** [comment] 2017-07-12 15:45
@pnicoll Writing custom HTML isn't a great solution, because it's fairly technical, fragile and a bad practice. I think what you're hitting here with tables is possibly a markdown limitation.

With this new version we can have smarter editing & rendering logic, to accommodate for those kind of situations.

We haven't yet done much work specifically on tables, because nobody has given us table-specific feedback so far.

I personally avoid putting too much content inside tables, and often opt for titles to group that content together. However, I don't know enough about your use-case to know if that makes sense for you.

Would love to jump on a quick call if you're free tomorrow or Friday to better understand your tables issue and see if we can fix it.

**Comment by nagim** [comment] 2017-07-12 15:51
@AaronO I have sent you table-specific feedback/suggestions before, too. If it got lost somehow in the meantime, let me know, I will resend it.

**Comment by pnicoll** [comment] 2017-07-12 15:59
@AaronO I understand that markdown tables are limited. If the smarter rendering logic can properly render non-breaking spaces to force column width (e.g. two tables with the same headers, so `|Column header 1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|Column header 2|` for both) then I'd be happy. Having different column widths for tables with the same headers makes it look like I don't care about formatting, when in fact it's the exact opposite.

Due to some of the content of my tables I often have to use HTML, and in markdown tables, everything in an `<ol>` or `<ul>` everything has to be in one line; there's no way around it, believe me, I've tried. So I end up with cells that look like this:


`|Template|Selection of workflow template to be tested directly, customizable and usable in the "By default" list or in the "library"<p></p><p>Default:</p><ul><li>2 levels approval</li><li>Parallel tasks</li><li>Simple approval</li><li>Simple request</li></ul><p>Library:</p><ul><li>Expense report</li><li>Software helpdesk</li><li>Investment application</li><li>IT Changes</li><li>IT Clearance application</li><li>Leave application</li><li>New Product Creation</li><li>Work Order</li></ul><p>A customized workflow template can be created and deployed on the server with the following folder and file structure:</p><p>\wfgen\App_Data\Templates\Processes\[language]\[folder name]\[process name]v[x].xml</p><p>Example:<p>\wfgen\App_Data\Templates\Processes \En\MyCompany\MY_PROCESSv1.xml</p><p>**Note:** Only processes with forms created with the built-in form designer can be used as workflow templates.|`

**Comment by AaronO** [comment] 2017-07-12 16:04
@nagim Nope Imre, I've still got the feedback you sent me regarding table cells and the ability to merge cells.

@pnicoll Do you have a link to share so I can see what it looks like ? Would be great if you had an example of desired output in raw HTML, compared to our current output.

**Comment by AaronO** [comment] 2017-07-12 16:07
@nagim @pnicoll Happy to talk more about tables, but we should probably move this conversation to https://github.com/GitbookIO/feedback, to not clutter this already long thread and go off-topic.

Would be great to have that feedback grouped into relevant issues (one on merged table-cells, another on alignment) with "current output/behavior" and expected output/behavior"

**Comment by lbeltrame** [comment] 2017-07-15 06:05
@AaronO Given the beta links, and the fact that even the mentions do not say much about the toolchain, the question is: will the toolchain keep on being open source, or will it be irreversibly tied to gitbook.com? I use the toolchain for convenience, and would never consider it if I can't self host the content painlessly (note: the competition has a similar and equally questionable stance).

**Comment by AaronO** [comment] 2017-08-03 12:38
@lbeltrame Sorry for the late reply, I was out of the office for a while following a medical operation.

**In short:** the toolchain will continue to exist in some form, but it needs to evolve.

Our goal is to enable teams to write great documentation (external API & Product docs, internal / team docs, ...). Everything else is a means to an end.

Samy and I built the first version of GitBook because we believed that documents should be simpler, smarter and richer. 

We did not stop at building the `toolchain` because we knew that by itself it was only a small part of what teams need (editing, hosting, collaboration, ...).

Given that we're a small team with limited resources, we have to chose our battles.
I don't think it would help our users or the project to focus on "self-hosting", it would only increase fragmentation and complexity ...

We're committed to building a great product for our users (that's simple, reliable and powerful), we believe in open-source and will continue to contribute (we're not looking to vendor-lock anyone) and have exciting new tech and APIs that are radically better for devs than what we have today (plugins, templating syntax, ...).

If you believe that an open-source project diverges from your goals, you have the freedom to fork it.

**Comment by lbeltrame** [comment] 2017-08-03 12:52
Basically, it's not going to be the focus, in some way, but you'll leave the toolchain open for others to improve, should the need arise.

That's fine, and I understand your needs. They simply do not align with mine (I'm using gitbook to write non-technical books, which are self-hosted), so I'll pick another tool (pandoc) with a different scope. 

That said, thanks for your work on GitBook because it did help me when I started writing.

**Comment by kirtan403** [comment] 2017-08-07 07:01
@AaronO That's really sad to here that, in some form the open toolchain will stop updating as you are focusing on building a product for consumer. Self hosting is one of the key factor which made gitbook popular, IMHO. 

I just hope that toolchain will be in the focus again..

**Comment by develar** [comment] 2017-08-31 10:23
Why I still use Gitbook instead of another static site generator — because without extra customisation you get really great documentation site. Just write docs and `gitbook build`. No need to tweak style, search another better default theme and so on. 

The only problem now — anchors navigation doesn't work reliably (a lot of reports about it in this issue tracker). And I see that in the beta version it is fixed.

I totally understand, that my usage is out of your product scope — I edit docs using IDE and publish to Netlify. But as far I see, in any case for gitbook.com some tool should be used to convert md to html. Not clear for me — why beta gitbook theme / new generator is not developed here as beta version/branch. Why users cannot use (and test) beta version of new generator.

Anyway, still hope that in the next several months it will be updated. Thanks for a great product.

**Comment by MrTrebron** [comment] 2017-11-18 11:03
For me it is the same as for @melvinchng 
I wrote emails regarding student discount without any answer.

Why should I recommand GitBook for my company when even a simple question stays unanswered?

**Comment by io41** [comment] 2017-12-08 17:03
The website and product is littered with email addresses for contacting support. Even twitter accounts. And no responses to any. At the very least you should remove all these reference if you're not going to bother replying. It's beyond frustrating working with such untransparent practices. Given the terribly misleading info (support contact, timelines, etc), lack of responses, I see no reason to trust any claims being made anymore. We're taking our business elsewhere.

**Comment by AaronO** [comment] 2017-12-08 17:27
@io41 Hi Tim,

Very sorry to hear that. I just went through our tickets and saw that you posted an issue regarding having a separate billing email (e.g: account department).

This period is particularly challenging, because we've been working extremely hard on a new product release (https://beta.gitbook.com), shipping in January. This release solves many of the large outstanding user pain points (product complexity, builds, reliability, etc ...).

The entire team's energy is focused on getting this release out the door, right now we're working on the migration tooling to allow users to self-migrate and prepare for mass migration.

It's frustrating as a founder (and I imagine it's equally frustrating for you) because I know that in the short term this has a negative impact on our users and customers, but we're doing this to improve the product in the long-run for everyone.

I've been stepping back from day-to-day product, now that we're approaching release, to grow the team to improve customer success amongst other things (we started this year with 4 people, we're now 8 and need a least a few more hires to serve our customers well).

Either way, we've failed you and I'm sorry for that.

**Comment by erlend-sh** [comment] 2018-01-05 08:59
Is GitBook still open source? If so, where can I track the code for the new beta product?

**Comment by merces** [comment] 2018-01-18 14:02
I believe the problem is that GitBook seems to be abandoned due the lack of updates (at least a blogpost to say that the team is working on a new release would make the difference). No company stays an year without giving their customers an update to say they're alive. If you reach the stage where your customers ask here if your product is still alive, then you are doing something wrong.

It's January, 2018 already and we haven't seen any update on GitBook blog about the beta. It's just weird giving the fact you told us the new version would be released this month. Also, there are hundreds of open issues and PR's with no answer. Sorry, you guys have a very nice product but it definitely looks dead to me.

**Comment by AaronO** [comment] 2018-01-18 14:07
Hi @merces, we didn't want to communicate without having something customers could actually test and use.
We're looking to do a public launch in a few weeks and have already been on-boarding teams with existing orgs on `gitbook.com` to test and gather feedback (If you have an org on `gitbook.com`, I'm happy to send you an invite)

You can see the beta's public changelog here: https://betadocs.gitbook.com/changelog

**Comment by Undistraction** [comment] 2018-01-21 15:54
@AaronO It's really great to hear Gitbook is still alive. I use it a lot and I'd pretty much given up hope on it ever being updated. In fact I found this issue typing 'gitbook alternative' into Google.  Hopefully the new release will address some of the bigger bugs (like the broken back button, tables, etc).

**Comment by xinity** [comment] 2018-01-22 13:45
In progress
Shipping in the next 1-2 weeks:

Public launch

Yayyyyyy can't wait!

**Comment by agauniyal** [comment] 2018-02-11 08:07
Its been more than 1-2 weeks 🤔

**Comment by blling** [comment] 2018-03-05 21:53
I just wonder if the next version of gitbook is still open source?

**Comment by zixia** [comment] 2018-03-06 16:36
I'm trying to find a solution to write documents for my project, it seems GitBook is a good candidate because it can host all the markdown files on GitHub with rich publishing plugins.

Looking forward to the public launch of the new version!

**Comment by fedorov** [comment] 2018-03-30 13:23
I wanted to follow up on my comment, and just say that although it can be difficult and frustrating at times, once you are able to get direct contact with one of the developers (and huge kudos to @AaronO for helping me on many occasions!) they are really getting on the issue, and are extremely helpful in trying to resolve it.

Over Slack, Aaron also pointed out that on the new GitBook site there is an Intercom chat icon (which is blocked by at least some ad blockers, so make sure you disable yours if you don't see it! I was not aware of its existence until now), and I was encouraged to establish direct contact via that channel. It sounds like account/repo specific issues should be reported there.

![image](https://user-images.githubusercontent.com/313942/38139067-d2ab3e7a-33fb-11e8-95a9-8102ddc049f3.png)

I completely understand the struggles of the small team, and at times their priorities are not aligned with what I would do or want to see done, but overall I remain hopeful about GitBook and I have not abandoned it for something else. Really look forward to the beta to be fully functional (I have yet to test it fully, now that I discovered the new support channel), and become stable.

**Comment by erlend-sh** [comment] 2018-04-04 00:08
> There are very very few large & successful open-source projects that are purely maintained by the community.

I wholeheartedly agree with that. For an open source product to compete with commercial offerings it needs to be backed by a company or some other commercial entity.

Meanwhile, it concerns me that we have not received an unambiguous reply regarding whether or not the GitBook core will continue to be open source, as is the case with your stable version. It would be a great shame GitBook went closed source, as it was looking to be the OSS wiki/docs contender that would seriously compete with the proprietary alternatives out there.

> With 8 people (only 4 last year ...), it's unsustainable / impractical to answer 1000s of questions from free users and build a product/team/business at the same time.

I'd like to be so bold as to suggest that your big bet on chat-only support was misguided. The Ghost project recently reached that conclusion:

https://twitter.com/JohnONolan/status/980872508395188224

**Comment by fedorov** [comment] 2018-04-04 19:37
> I'd like to be so bold as to suggest that your big bet on chat-only support was misguided.

I thought I am an outlier struggling with Slack! Thank you for sharing the Ghost reference.

**Comment by istiti** [comment] 2018-04-18 07:58
I agree that opensource with commercial offering need to be backed by company. But ideas/feat. request from users on github should be taken ! 

The question is: today i don't know how I install and test locally gitbook4, I don't want currently use gitbook.com (will move in next couple of weeks ) I just want test gitbook4 locally. Current editor and current gitbook is a little bit buggy. 

all new features @AaronO  notices seems wow!

Can't we create beautiful readme / blog post about it , thanks

**Comment by pnicoll** [comment] 2018-04-18 12:52
I, too, would like to be able to test the new version as well before upgrading my organization. As @istiti said, the current web and desktop editors are buggy and quirky; as such, I don't want to upgrade only to encounter new issues that I have to isolate and fix or work around in a panic while preparing the documentation for our next product release. So is this possible?

**Comment by istiti** [comment] 2018-04-18 13:39
@pnicoll seems the new SaaS gitbook version is web hosted on gitbook.com not cli anymore, this is the big change here afaik. Dommage with cli i put my data on my computer not over web. The awesome would be have cli limited to famous markdown documentations (plugins oriented) and have gitbook commercial with official implementations but don't think we will have this

**Comment by Aaronius** [comment] 2018-04-26 01:10
Just here to say that I'm a new user and my experience has been really fantastic, especially the support. The product is super-slick and was much needed by my team. I've been really impressed and can understand why it took "so long" to get out the door. Kudos to your team. 👍

**Comment by jamesvanie** [comment] 2018-04-28 20:33
@AaronO , just caught the new update and it looks great. 

How can I migrate all of my old files over to the new interface? Thanks.

**Comment by ketozhang** [comment] 2018-05-05 01:45
@jamesvanie See ["Migrating from the previous version"](https://docs.gitbook.com/getting-started/migrating-from-the-previous-version)

**Comment by royhodge** [comment] 2018-05-14 21:30
Really enjoy Gitbook, Are there any plans to integrate gitpitch alongside gitbook?

**Comment by neumayr** [comment] 2018-05-25 08:12
@AaronO Will the new GitBook v4 also be available as `npm` package at some later point?

📦https://www.npmjs.com/package/gitbook

**Comment by istiti** [comment] 2018-05-25 12:51
@neumayr no never again sadly. so if you want your doc to be safe or internaly in your network (no on internet) you can't you must write your content on their commercial site. They telling that : improvement to handle all case and avoid hack plugin.

Some people would be happy but I completly disagree.
Taking wordpress as example.
**wordpress.org** is installable and they have millions of plugins in their installable version, and wordpress covers 30% of the web in the world ! 
**wordpress.com** is online and allow you to create simple hosted blog without these plugins.

I think this is bad choice IMHO (even if gitbook.com is easy2use) we should have installable version and ability to connect with any SGBD **AT LOCAL**

**Comment by sarahsga** [comment] 2018-06-06 15:38
Unfortunately, Gitbooks are not print-friendly anymore :( They're great for online use but not for printing :(

**Comment by AaronO** [comment] 2018-06-06 15:57
@sarahsga PDFs are coming

**Comment by FibreFoX** [comment] 2018-06-06 16:38
Stupid idea: how about closing all the "is this project alive"-issues? Despite of some changes of dropping on-premise solution, this large issue makes it not really good looking for gitbook. And if there are such mayor changes, how about closing old pull-requests? Some cleanup would be very effective for outsiders not wanting to get in touch with projects having long-lasting pull-requests and issues.

**Comment by FichteFoll** [comment] 2018-06-06 20:51
From what @neumayr quoted, it seems pretty clear to me that the open-source (or the self-hostable) version of gitbook will be abandoned, which is precisely what I wanted to know. For my use case, I am not interested in a gitbook-hosted "book" or website and I don't intend to pay for something I plan to provide for free.

For now, I will likely continue using gitbook because it still stands out compared to the competition (mostly due to the amount of plugins adding functionality to it). However, when I end up running into dead ends or bugs that would involve a lot of work to solve, I'll definitely re-evaluate the decision.

Still, thanks for providing the (old) option of a self-hostable static site generator.

**Comment by f-r-i-t-z** [comment] 2018-06-12 18:51
So!
Gitbook/gitbook editor was one of best platforms to  authoring both technical and home documentation/books etc.
Was easy, Productive, using markdown.
Now become a closed system, only with WYSIGY imput, with an complicated and non intuitive interface that rig us off from our markdown docs.
Sorry!
There is plenty of very good and stable/mature platforms for online authoring outside there using this same concept that the gitbook want now.

Sad news...

Yet I'm to use the gitbook CLI ( split code/preview cant works for a while now and some themes) and gitbook editor for windows together the gitbook for documentation structure.

YET starting to migrate to ATOM by editor and look around to create a kind of pandoc routine to convert my docs..

I hope someone fork the opensource / editor and still maintain this.
From a brilliant future to end with this? SAD.

**Comment by pnicoll** [comment] 2018-06-12 19:10
I'm happy to continue using the legacy version, which has made documentation so much easier for me, but we won't be upgrading to the new version for the following reasons:

1. No markdown editor. I very often copypaste .md content prepared by our developers in GitHub and then work on it in GitBook. I need to be able to work in markdown code with the preview pane on the right.

2. No PDF generation (yet). We absolutely need this for our clients.

3. No desktop app.

**Comment by fedorov** [comment] 2018-06-12 19:17
@pnicoll thanks for the comments. I have not yet migrated the content to the new version, and was going to look specifically how they handle markdown in the new version, and how I could edit the content without using their WYSIWYG editor. Good to keep in mind it's been axed, and I share your concern on that one.

**Comment by AaronO** [comment] 2018-06-12 19:17
@pnicoll Just a quick update and some comments:

1. An update we released 2 days ago, now allows you to paste in markdown
2. PDFs are coming, we're working on polishing it (to handle larger docs, with 500+ pages, etc ...)
    - The first will release will first support public docs
3. This is planned

**Comment by Undistraction** [comment] 2018-06-12 19:20
@AaronO Reading between the lines I'm guessing you have no plans to support a pure markdown editor mode - only WYSIWYG?

**Comment by AaronO** [comment] 2018-06-12 19:57
@Undistraction @pnicoll Our goal is to provide our users with a great editing experience (whatever implementation should be measured against that goal, wether it's a WYSIWYG or a Markdown editor).

WYSIWYGs aren't usually very powerful and Markdown editors aren't usually very simple.

The editor we've built in the v2 aims to be a good balance of simplicity and power, essentially a unified editor that provides the best of both worlds.

If we see that the "unified editor" approach really isn't working, then I think we would need to be pragmatic and reconsider other options.

So far, a large portion of users really like the simplicity of the new editor and how it can seamlessly do things not supported in vanilla Markdown (embeds, rest api-methods, hints/callouts, image captions, ...).

I think we really need to understand the specific issues you have with the unified editor. Figure out if those are things that can be fixed or if they do really require a different editing experience.

If you could both list out the top 3 issues / shortcomings you have with the new editor, that would be extremely helpful and appreciated !

**Comment by pnicoll** [comment] 2018-06-12 20:09
@AaronO I need to be able to work in markdown code. As long as we can keep using the legacy version indefinitely, it's neither here nor there.

**Comment by fedorov** [comment] 2018-06-12 20:13
@pnicoll I kind of also understand the sentiment of @AaronO, since markdown is not expressive enough to support specific features he mentioned, but are often requested by the users.

Could there be a middle ground, where a certain book or content component could be marked as "vanilla markdown", and where all the GitBook-specific features would not be expected, so users could maintain compatibility with the external, markdown-only processes?

**Comment by istiti** [comment] 2018-06-12 20:39
We need pdf

**Comment by FibreFoX** [comment] 2018-06-12 20:58
@AaronO as I'm kinda feel ignored, why not closing all old issues, or making this repository "archived"/readonly? Having "both worlds" online makes this project seemingly active, but as it's not activly developed anymore ... 

Please close this issue, with a final answer like "we are going different ways now, nothing to see here anymore"?!

**Comment by develar** [comment] 2018-06-24 08:48
Good luck to Gitbook team with a new product, but if you need offline static generator, I suggest https://www.mkdocs.org Default theme maybe not so cool as Gitbook, but there is [material theme](https://squidfunk.github.io/mkdocs-material/) that allow you to easily specify [theme colour](https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette)

**Comment by YoungJaeChoung** [comment] 2018-07-17 12:44
I`m new to gitbook and have a trouble on using gitbook.

Editing on the web is extremely slow.
Editing Program is not working on login.

I really want to use gitbook. But it makes me crazy.

Is Gitbook still alive...? (Ask Again)

**Comment by istiti** [comment] 2018-07-17 13:09
gitbook has been acquired not by a multinational but by a new way of thinking needs. donno maybe durning some vacations the real click come on (joke)

**Comment by aleung** [comment] 2018-07-18 10:45
@AaronO  Since you are not going to open source the GitBook V2, you'd better rename this repo to `gitbook-legacy` to not make people confusing.

**Comment by Undistraction** [comment] 2018-07-18 12:17
For anyone else looking for an alternative now that Markdown support has been partly removed, I'd recommend taking a look at [Gatsby](https://www.gatsbyjs.org/). It's a static-site generator and not documentation-specific, but can easily be used to generate docs and has first-class Markdown support. There are lots of great starters available. When paired with [Contentful](https://www.contentful.com/) or [Zeit Now](https://zeit.co/now) or Github Pages it's a very slick workflow.

**Comment by develar** [comment] 2018-07-18 12:37
> When paired with Contentful or Zeit Now or Github Pages it's a very slick workflow.

For hosting I recommend [Netlify](http://netlify.com/) (free, one-click ssl for custom domain).

**Comment by Undistraction** [comment] 2018-07-18 14:01
@develar I actually meant Netlify instead of Contentful. Thanks. There is also a great CMS for Netlify for editing content which makes collaboration easy.

**Comment by pmkay** [comment] 2018-07-18 17:50
did gitbook get hacked? why is it marked as harmful?

![image](https://user-images.githubusercontent.com/4557167/42898539-4be59614-8a78-11e8-8cfc-52d234b5980c.png)

**Comment by pmkay** [comment] 2018-07-18 19:14
noted, thanks @fedorov

**Comment by ervinb** [comment] 2018-07-18 19:16
Just to chime in on the above, if you're reading a book and can't load the page, just do a Google search with the full URL, and click on the green arrow (after the link) > Cached.

**Comment by Undistraction** [comment] 2018-07-27 09:39
For anyone else looking for an alternative now that Gitbook has removed Markdown editing, [corilla](https://corilla.com)/ looks pretty good and has a great free plan. It's in Beta at the moment and has a few rough edges but does everything I need it to do.

**Comment by YoungJaeChoung** [comment] 2018-08-07 01:02
@Undistraction 

does corilla support latex syntax...?

**Comment by Undistraction** [comment] 2018-08-07 05:53
@YoungJaeChoung I ended up ditching corilla and moving to [notion.so](https://www.notion.so/) which is exactly what I've been looking for for years. I can't recommend it enough. And it support LaTeX. It's the first thing I've used for ages which has really blown me away. s

**Comment by yjchoung1** [comment] 2018-08-13 00:30
@Undistraction Thank you for the information about a new site. I will try it. Thanks!!! x 100

**Comment by dskvr** [comment] 2018-08-24 11:17
Since it's obvious Gitbook has gone in a different direction, completely nixing statically generated docs and resulting in making their name "GitBook" completely irrelevant, shall we start an effort to fork, rename and maintain our beloved "Legacy" Gitbook?

**Comment by nreynis** [comment] 2018-09-17 07:37
I agree Gitbook V2 and legacy Gitbook are two entirely different products, and most of the features that made me interested in it are gone in the new version.

**Comment by pnicoll** [comment] 2018-09-17 13:53
All I wanted was a markdown pane, or at least to be able to toggle between WYSIWYG and markdown pages. Potential use case: Developer wants their now-properly-formatted `.md` code back for a readme. I copy the rendered WYSIWYG from the new GitBook. What will be pasted? I asked this a LONG time ago and never got an answer.

I can live without a desktop editor, and I figure most of our clients will read the documentation online, not generating PDFs, but **I cannot work in a markdown-based editor that does not display markdown code**.

**Comment by dskvr** [comment] 2018-09-26 11:16
Let's fork it guys.

**Comment by istiti** [comment] 2018-09-26 11:34
@dskvr no dude you're wrong,  they call that **innovation**, they call that **you need your doc online hosted by them**, they call that **we are in best position to know best option we can't continue with hacky plugin** while wordpress can...

**Comment by nreynis** [comment] 2018-09-27 09:30
@dskvr You know people still got to make a living. If they wan't to push their product all the way on the SaaS road that's their call. The previous version probably wasn't generating enough paying customers to sustain the company.

**Comment by morinted** [comment] 2018-09-30 02:27
I was looking to replace my legacy gitbook site with some custom Gatsby or React-Static site, but just now I discovered **[Docusaurus](https://docusaurus.io/en/)**.

Honestly, this is what I've always wished Gitbook was. Basically, it's got all the same major features (static site generation, pretty sidebar, mobile-view, markdown content) **except** it's written in React and lets you write custom components and the like as part of your docs. Perfect!

Only gripe: no PDF export.

**Comment by dskvr** [comment] 2018-10-31 05:01
@maksimyurkov I've been leaning towards VuePress.

@morinted Docusaurus looks good at first glance, but I'm not seeing an interactive API (like gitbook had and VuePress has) ... Only feature I'm seeing that's not natively supported by VuePress is Versioning.

**Comment by energyd** [comment] 2018-11-05 23:42
simple question, how do I migrate all my docs from legacy to new gitbook? (or to any of the new ones you guys mentioned above, VuePress, etc..)

**Comment by ketozhang** [comment] 2018-11-05 23:53
For VuePress or Docosaurus is there a way to simply use the directory stucture of my markdown files say all in `docs/` to side nav.

A simple use case is a book where in `docs/` you have directories for each chapter.

A more specific use case for myself is I have topics and subtopics within my book (it's a Markdown notebook).

**Comment by morinted** [comment] 2018-11-06 00:52
When migrating to VuePress I had to redo my sidebar in config.js:
https://vuepress.vuejs.org/default-theme-config/#sidebar

There is documentation for "groups" and nav within the page. Good luck!

**Comment by oxr463** [comment] 2019-03-18 16:14
> 
> 
> Anyone find an alternative to gitbook?

There are plenty of [other great static-site generators][1] out there. I actually really like the look of gitbooks, so much in fact, that I [ported][2] it to [Mkdocs][3].

[1]: https://www.staticgen.com
[2]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes#gitbook-theme
[3]: https://www.mkdocs.org

**Comment by dariushazimi** [comment] 2019-03-26 22:41
I am getting this error when trying to login to gitbook client on macOS.

Any idea? Anyone,  commented on the open issue on gitbook repo but I don't see any activity there at all.
Unauthorized New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com

os: macOS Mojave
git version 2.19.0
Created a new account on gitbook.com site.
Logged in successfully on gitbook.com
downloaded the client.
Can't login.
Tried to login with github and google but both have the same issue.

401 Unauthorized New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com

https://github.com/GitbookIO/gitbook/issues/2119

Unauthorized New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com

![Screen Shot 2019-03-25 at 7 13 00 PM](https://user-images.githubusercontent.com/622048/55038317-cbb9a080-4ff6-11e9-97aa-f6ed5c3e951e.png)

**Comment by SteveBenner** [comment] 2019-04-09 18:10
I normally wouldn't go out of my way to comment on something like this, but right now I'm simply flabbergasted. I was using Gitbook a few years back and it was great. I was just now going to recommend Gitbook to a friend as an analogous solution to [Flatdoc](https://ricostacruz.com/flatdoc/), but upon visiting their site again my confusion just gave way to sadness and vexation.

The question 'is Gitbook still alive?' should, I think, be answered as a definitive **NO**. This new platform is _**entirely**_ incomparable to the original software, and yet heralded as 'version 2' somehow. [Reading through the list of 'important changes' from the original](https://docs.gitbook.com/v2-changes/important-differences), it became clear they had literally removed all of the features I had found unique, useful, and delightful software to begin with.

As a user, I'm not upset at them for changing--there are plenty of other solutions out there, and I have nothing against a team wanting to monetize their creation. This transformation has been completely misleading, though--I don't see how anyone can call the new platform 'version 2' of the original Gitbook when it is nothing of the sort. **_This is why rebranding exists_**. The original creation should have been rebranded, seeing as it is now an entirely different platform.

On their site they say:

> Today we empower teams of all sizes to build great internal & external docs

Yet no one is going to be empowered if they, like me, are uninterested in the new platform.

**Comment by piranna** [comment] 2019-04-09 18:14
So, @SteveBenner... maybe is it time to create a fork, like Mate Desktop did with Gnome 2? :-)

**Comment by SteveBenner** [comment] 2019-04-09 18:16
> So, @SteveBenner... maybe is it time to create a fork, like Mate Desktop did with Gnome 2? :-)

Yes.

**Comment by piranna** [comment] 2019-04-09 18:28
Count with me.

**Comment by SamyPesse** [comment] 2019-04-09 18:29
@piranna @SteveBenner I understand your position, but I'm locking this issue as it's not bringing any value (on either side).

The code source for the legacy CLI is and will always be available on GitHub.
The new GitBook.com has a compatibility with it using our GitHub sync and brings many large improvements that were not possible with the CLI.

We'll continue focusing our efforts in building the best documentation platform for all teams with GitBook.com.

**Closed by SamyPesse** 2019-04-09 18:29 UTC
