### ISSUE TITLE
My gitbook is now showing a version one month ago

### ISSUE THREAD

**Issue by colingonglin** [GitbookIO/gitbook#1509] opened 2016-08-30 09:24 UTC
Version: Legacy version 2.6.7

My gitbook is now showing a version that is one month ago. The book is out of date now.

And I find that my lastest checkin is shown at the bottom of the list and the checkin one month ago is shown at the top of the list. I think this is something to do with this issue.

![image](https://cloud.githubusercontent.com/assets/12727213/18083625/818f9b1c-6ed6-11e6-952a-086e4f3f921d.png)

![image](https://cloud.githubusercontent.com/assets/12727213/18083627/8460e544-6ed6-11e6-8025-410595605633.png)

**Comment by SamyPesse** [comment] 2016-08-30 09:26
Duplicate of #1508 and GitbookIO/feedback#161

**Closed by SamyPesse** 2016-08-30 09:26 UTC
Labels: duplicate
